### PR TITLE
Use cached informers clients

### LINKED ISSUE #72: main loop is very slow due to NodeGroupForNode performing a full machine list
**What happened**:
I've been investigating why cluster-autoscaler is very slow in our cluster, with hundreds of managed nodes taking 5m+ to perform a single reconcile loop.

After digging for a while with `-v8`, it seems that we're getting throttled due to the large number of requests for `machines` against the apiserver. It looks like the main culprit here is the `NodeGroupForNode`/`ReferenceFromProviderID` implementation, which does a basic full list of the machines for each node as the cluster-autoscaler goes through them. This then gets throttled by client-go down to 200ms per request.

**What you expected to happen**:
The mcm cloud provider shouldn't be doing straight GETs of kubernetes resources. It should be using shared informers or another caching mechanism to efficiently query the state of the apiserver.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
If I have time, I will try to put together a PR to improve this.

**Environment**:

### PR DESCRIPTION
**Pull request by prashanth26**
**What this PR does / why we need it**:
This PR switches use from individual list calls to using cached informers. Definitely an important optimization we have missed. 

**Which issue(s) this PR fixes**:
Fixes #72 

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
Switch to using cached informers to fetch cloud provider details more optimally.
```
```noteworthy user
Enable configuraiton of flags such as `control-apiserver-burst`, `control-apiserver-qps`, `target-apiserver-burst`, `target-apiserver-qps` and `min-resync-period` for kubernetes client configurations while fetching objects for MCM cloud provider.  
```

### CODE REVIEW

**Comment by prashanth26** [comment]
/hold
I have just made the changes and opened it up for suggestions. Currently not sure how this has to be done - https://github.com/gardener/autoscaler/pull/73/files#diff-4f368ce653a560c0ab66089e189d923883e88c189d8af47469ff5001218c6795R176-R180. @amshuman-kr - you might have thoughts here? 

I am yet to test the changes, will probably do that tomorrow. Thanks.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 1]
```diff
@@ -81,10 +83,20 @@ type McmManager struct {
 	namespace               string
 	interrupt               chan struct{}
 	discoveryOpts           cloudprovider.NodeGroupDiscoveryOptions
-	machineclient           machineapi.MachineV1alpha1Interface
-	coreclient              kubernetes.Interface
+	machineClient           machineapi.MachineV1alpha1Interface
+	coreClient              kubernetes.Interface
 	machineDeploymentLister machinelisters.MachineDeploymentLister
-	machinelisters          machinelisters.MachineLister
+	machineSetLister        machinelisters.MachineSetLister
```
Comment (amshuman-kr) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:112]: Why not nodeInformers too? It is used [below](https://github.com/gardener/autoscaler/pull/73/files#diff-fc87dde41e1a7abff0b0bc24dbabc258ac3d594a346b8f01e020b9e7f9775440R443).

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 2]
```diff
@@ -392,29 +428,29 @@ func (m *McmManager) DeleteMachines(machines []*Ref) error {
...
-	//machinelist, err := m.machinelisters.Machines(m.namespace).List(labels.Everything())
-	machinelist, err := m.machineclient.Machines(m.namespace).List(context.TODO(), metav1.ListOptions{})
+
+	machineList, err := m.machineLister.Machines(m.namespace).List(labels.Everything())
 	if err != nil {
 		return nil, fmt.Errorf("Unable to fetch list of Machine objects %v", err)
 	}
 
-	nodelist, err := m.coreclient.CoreV1().Nodes().List(context.TODO(), metav1.ListOptions{})
+	nodeList, err := m.coreClient.CoreV1().Nodes().List(context.TODO(), metav1.ListOptions{})
```
Comment (amshuman-kr) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: See [above](https://github.com/gardener/autoscaler/pull/73/files#diff-fc87dde41e1a7abff0b0bc24dbabc258ac3d594a346b8f01e020b9e7f9775440R89).

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 3]
```diff
@@ -223,27 +249,37 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
 	}, nil
 }
 
-//Cleanup does nothing at the moment.
-//TODO: Enable cleanup method for graceful shutdown.
+// Refresh refreshes the lister caches
+func (m *McmManager) Refresh() error {
+	var stopCh <-chan struct{}
```
Comment (amshuman-kr) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: `stopCh` is never closed. Ideally, this should be linked with the termination of the main routine (signal handler channel?).

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 4]
```diff
@@ -223,27 +249,37 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
...
+	if !cache.WaitForCacheSync(stopCh, m.machineDeploymentSynced, m.machineSetSynced, m.machineSynced, m.machineClassSynced, m.azureMachineClassSynced, m.awsMachineClassSynced) {
```
Comment (amshuman-kr) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Ideally, `WaitForCacheSync` should be called only once during startup and not during every reconcile/main loop.
Maybe it is enough to do this [here](https://github.com/gardener/autoscaler/pull/73/files#diff-fc87dde41e1a7abff0b0bc24dbabc258ac3d594a346b8f01e020b9e7f9775440R172) once and then do nothing in this `Refresh` func because once cache is synced it will be kept up-to-date by the watch connections of the informers.

**Review by amshuman-kr — CHANGES_REQUESTED** [review]

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 4 above)
Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Now checking only on [intialization here](https://github.com/gardener/autoscaler/pull/73/commits/a7d47db2a052a8b144e361afe5dae97e9aeea612)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 3 above)
Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: [This is the function that invokes](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/builder/builder_all.go#L77) the cloud provider creation. I don't see any channels being passed from here. So not sure what's the best way here. I have closed the channel by [defer for now](https://github.com/gardener/autoscaler/pull/73/commits/a7d47db2a052a8b144e361afe5dae97e9aeea612#diff-fc87dde41e1a7abff0b0bc24dbabc258ac3d594a346b8f01e020b9e7f9775440R173). Please recommend if we can do any better.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 1 above)
Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:112]: Good point. Something even thought about after going to sleep last night. 

I tried changing this today. However, was running into a vendoring mess. Let me see if i can fix this.

Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:112]: As suggested, I have switched to nodeInformers [here](https://github.com/gardener/autoscaler/pull/73/commits/f8a13a52629f14399ead355ea4018a49a55a203b) as well. 

There is an optimization of reusing code here to use [these MCM libraries](https://github.com/gardener/machine-controller-manager/tree/master/pkg/util/clientbuilder) to build clients. However, while trying to make this change I am running into vendoring mess. The cause for the vendoring mess are two reasons, 
1. Mismatch in k8s versions used by MCM and Autoscaler. 
2. Go lang version on my system is `1.16` versus the required `1.15`. 

Both these points can be overcome using backs like rebuilding clients for MCM locally on 1.19 and switching the build on docker. However, in the interest of time and efforts I would like to leave out this optimization to post picking of [MCM k8s version update](https://github.com/gardener/machine-controller-manager/issues/402) which would ease solution this issue. For now [this is redudant code](https://github.com/gardener/autoscaler/pull/73/files#diff-a1da33377c26d5adb1f79d69949633c74af97a70cdb0340ae5eb7169750494d6R1-R95) which we should get rid of in future. Shouldn't affect the working IMO.

Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:112]: Also have gotten rid of the coreClient as it is no longer used [here](https://github.com/gardener/autoscaler/pull/73/commits/f8a13a52629f14399ead355ea4018a49a55a203b#diff-fc87dde41e1a7abff0b0bc24dbabc258ac3d594a346b8f01e020b9e7f9775440L87)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 5]
```diff
@@ -102,9 +107,25 @@ type nodeTemplate struct {
...
+	targetBurst  *int
+	targetQPS    *float64
+)
+
+func init() {
+	controlBurst = flag.Int("control-burst", rest.DefaultBurst, "Throttling burst configuration for the client to control cluster's apiserver.")
+	controlQPS = flag.Float64("control-qps", float64(rest.DefaultQPS), "Throttling QPS configuration for the client to control cluster's apiserver.")
+	targetBurst = flag.Int("target-burst", rest.DefaultBurst, "Throttling burst configuration for the client to target cluster's apiserver.")
+	targetQPS = flag.Float64("target-qps", float64(rest.DefaultQPS), "Throttling QPS configuration for the client to target cluster's apiserver.")
+}
```
Comment (prashanth26) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: @amshuman-kr - As suggested, I have added rate-limiting parameters for both the APIServers as flags.

**Review by prashanth26 — COMMENTED** [review]
I am done with all my changes. Open for review. 

/invite @AxiomSamarth

**Comment by prashanth26** [comment]
Also ran a couple of tests locally. Saw the main loop time reducing from `5-6s` to below `300ms` with a 2 machine cluster. I suspect the results would be much better with a larger cluster which i will try to validate soon.

**Comment by jsravn** [comment]
@prashanth26 I am happy to test this as well on our large cluster. Looking forward to this!!

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 6]
```diff
@@ -114,56 +135,93 @@ func createMCMManagerInternal(discoveryOpts cloudprovider.NodeGroupDiscoveryOpti
...
+		azureMachineClassInformer.HasSynced,
+		machineClassInformer.HasSynced,
+		machineInformer.HasSynced,
+		machineSetInformer.HasSynced,
+		machineDeploymentInformer.HasSynced,
+		nodeInformer.HasSynced,
+	}
+	if !cache.WaitForCacheSync(m.interrupt, syncFuncs...) {
+		return nil, fmt.Errorf("Timed out waiting for caches to sync")
+	}
```
Comment (jsravn) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:317]: Does this block indefinitely if you don't have all of the CRDs in your cluster?

**Comment by jsravn** [comment]
No luck with this PR yet, cluster-autoscaler seems to hang at startup and not do anything.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 6 above)
Comment (jsravn) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:317]: We might need a more explicit failure in that case, because previously cluster-autoscaler wouldn't complain. Probably it should log a fatal fault if any of the CRDs are missing.

Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:317]: This is a good catch. I didn't think about this case. I have fixed it with this [here](https://github.com/gardener/autoscaler/pull/73/commits/3b73331aa56854d564ce4eba429dee02f58d8521#diff-fc87dde41e1a7abff0b0bc24dbabc258ac3d594a346b8f01e020b9e7f9775440R163-R207). I hope the changes on [this commit](https://github.com/gardener/autoscaler/pull/73/commits/3b73331aa56854d564ce4eba429dee02f58d8521) captures your concerns.

**Comment by prashanth26** [comment]
Hi @jsravn ,

I have tried to address your concern with the last commit. PTAL and let me know if it fixes the problem.
CA image: `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler:v0.15.0-dev-3b73331aa56854d564ce4eba429dee02f58d8521` to help with your testing. If you need one.

**Comment by jsravn** [comment]
Thanks @prashanth26, it seems to be working for me now. There is a massive improvement. Main loop time has dropped from several minutes to <1s. I'm now seeing scale ups almost instantly once pods go unschedulable, whereas before it took several minutes. This is great!

I wonder if mcm has a similar issue?

**Comment by prashanth26** [comment]
> Thanks @prashanth26, it seems to be working for me now. There is a massive improvement. Main loop time has dropped from several minutes to <1s. I'm now seeing scale ups almost instantly once pods go unschedulable, whereas before it took several minutes. This is great!

I am glad to hear this. I think the fix seems to be working then. If you would be kind enough to review/approve this PR it would be great to get validation from your end. 

> I wonder if mcm has a similar issue?

No, this is not an issue with MCM. Because MCM uses cached informers. Refer [here](https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/controller.go#L138-L164). There had been minor fixes where we had used APIServer calls instead of cached lister calls. However, those issues have been fixed.

**Comment by prashanth26** [comment]
I just ran these changes across a cluster with 300 nodes. And here are the cluster-autoscaler metrics with same number of main loops run = 109.

Before this PR
```
# HELP cluster_autoscaler_function_duration_quantile_seconds [ALPHA] Quantiles of time taken by various parts of CA main loop.
cluster_autoscaler_function_duration_quantile_seconds{function="main",quantile="0.5"} 732.165734223
cluster_autoscaler_function_duration_quantile_seconds{function="main",quantile="0.9"} 737.854896243
cluster_autoscaler_function_duration_quantile_seconds{function="main",quantile="0.99"} 737.854896243
cluster_autoscaler_function_duration_quantile_seconds_sum{function="main"} 80158.217258627
cluster_autoscaler_function_duration_quantile_seconds_count{function="main"} 109
# HELP cluster_autoscaler_function_duration_seconds [ALPHA] Time taken by various parts of CA main loop.
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.01"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.05"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.1"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="1"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="2.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="7.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="10"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="12.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="15"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="17.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="20"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="22.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="25"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="27.5"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="30"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="50"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="75"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="100"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="1000"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="+Inf"} 109
cluster_autoscaler_function_duration_seconds_sum{function="main"} 80158.217258627
cluster_autoscaler_function_duration_seconds_count{function="main"} 109
cluster_autoscaler_last_activity{activity="main"} 1.61838e+09
```

After this PR
```
cluster_autoscaler_function_duration_quantile_seconds{function="main",quantile="0.5"} 0.138423107
cluster_autoscaler_function_duration_quantile_seconds{function="main",quantile="0.9"} 0.246456598
cluster_autoscaler_function_duration_quantile_seconds{function="main",quantile="0.99"} 0.306613683
cluster_autoscaler_function_duration_quantile_seconds_sum{function="main"} 17.683218733000007
cluster_autoscaler_function_duration_quantile_seconds_count{function="main"} 109
# HELP cluster_autoscaler_function_duration_seconds [ALPHA] Time taken by various parts of CA main loop.
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.01"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.05"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.1"} 0
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="0.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="1"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="2.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="7.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="10"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="12.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="15"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="17.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="20"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="22.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="25"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="27.5"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="30"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="50"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="75"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="100"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="1000"} 109
cluster_autoscaler_function_duration_seconds_bucket{function="main",le="+Inf"} 109
cluster_autoscaler_function_duration_seconds_sum{function="main"} 17.683218733000007
cluster_autoscaler_function_duration_seconds_count{function="main"} 109
cluster_autoscaler_last_activity{activity="main"} 1.618381583e+09
```

Main loop execution time has reduced from `~740s` to under `0.5s`. 
cc: @amshuman-kr

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 7]
```diff
@@ -102,9 +130,18 @@ type nodeTemplate struct {
...
 
+func init() {
+	controlBurst = flag.Int("control-apiserver-burst", rest.DefaultBurst, "Throttling burst configuration for the client to control cluster's apiserver.")
+	controlQPS = flag.Float64("control-apiserver-qps", float64(rest.DefaultQPS), "Throttling QPS configuration for the client to control cluster's apiserver.")
+	targetBurst = flag.Int("target-apiserver-burst", rest.DefaultBurst, "Throttling burst configuration for the client to target cluster's apiserver.")
+	targetQPS = flag.Float64("target-apiserver-qps", float64(rest.DefaultQPS), "Throttling QPS configuration for the client to target cluster's apiserver.")
+}
+
 func createMCMManagerInternal(discoveryOpts cloudprovider.NodeGroupDiscoveryOptions) (*McmManager, error) {
+	const resyncPeriod = 12 * time.Hour
```
Comment (jsravn) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: I suspect this is too large. kubelet for example [uses a 15 minute resync period](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubeletconfig/watch.go#L42), same with kube-proxy. It is configurable in kube-proxy as `config-sync-period`, so maybe we want the same here. I think the issue is that watches can silently drop in some configurations (for example, if you're routing apiserver traffic via a proxy like an AWS ELB which happen to restart/die). The resync is necessary to detect these stale watches.

**Review by jsravn — COMMENTED** [review]
lgtm apart from one comment

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 7 above)
Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: The concern you bring to the table is a valid one. Thanks for this. I looked through several controllers including the [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), Kubelet, kube-proxy and other controllers. The general trend I see is that the cache resync period is configured to controllers to 12hours including the KCM in the link above. However, like you have mentioned for kubelet and kube-proxy the values are 15mins. 

I agree with your concern about the stale cache however, resync of cache every 15mins seems CPU intensive to me (Maybe valid for controllers like Kubelet which are known to be CPU intensive in nature). I even checked other Gardener controllers including the MCM that seems to be using 12 hours and working without problems until now. 

Finally, I looked at the CA inbuilt caches, and looks like they are using a [static 1hour](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/utils/kubernetes/listers.go#L246). So keeping it aligned with the other parts of CA how about we align it to default to 1hour for now. And as always this flag is configurable and can be tweaked if we find it suboptimal in the future? 

Made the changes for the same here -https://github.com/gardener/autoscaler/pull/73/commits/607e70ba551f1d089922c6b199997ec8b8ac7e0c.

Comment (jsravn) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Ah you're right. I wonder why it's 12h in controller manager. Seems like we looked at opposite things :). Maybe it's not an issue in that case.

Comment (jsravn) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: It's probably because controller manager has many more watches potentially than kubelet or kube-proxy. That's my guess at least.

Comment (prashanth26) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Indeed :) I have taken a middle ground of `1hour` for now. Also considering the cluster autoscaler configs above. I hope it seems reasonable for now.

**Review by jsravn — APPROVED** [review]
lgtm!

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 3 above)
Comment (amshuman-kr) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Hmm... the signal handling in non-existent even in the main function and the [leader election loss handling](https://github.com/gardener/autoscaler/blob/7b07db383f0c644f16eb8e59c1614e9a22b9103a/cluster-autoscaler/main.go#L434) is also quite amusing :-)

I guess this is the best we can do for now.

**Review by amshuman-kr — APPROVED** [review]
Thanks for the change @prashanth26! And sorry for the delay in reviewing. LGTM
