### PR TITLE
Handle edge case as described in issue #328

### LINKED ISSUE #328: Fix edge case mentioned in https://github.com/gardener/autoscaler/pull/215
**What happened**:
In live issue 5658, we see that the edge case mentioned in the PR #215 is hit and an incorrect machine object is deleted.

**What you expected to happen**:
The correct machine object should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
Solution:-
1. If scaling down of MCD fails, reset the priority of the corresponding machines
2. In Refresh Method, do the following:-
    1. Get the mcd replicas, r1.
    2. availMachines = Total Machine Objects - Machines having Prio 1 Annotation
    3. If r1 == availMachines, return
    4. If r1 > availMachines, then order machines with prio 1 annotation based on Creation Timestamp(desc order).
    5. From the above ordered list, pick up r1-availMachines and reset their priority.

**Environment**:

### PR DESCRIPTION
**Pull request by rishabh-11**
**What this PR does / why we need it**:
This PR modifies the `Refresh` method of CA to reset the priority annotation on the machine objects only if the number of annotated machines is more than desired. The desired count is `totalMachines - mcd.Spec.Replicas`. `Terminating` and `Failed` machines are excluded while calculating the total number of annotated machines.

**Which issue(s) this PR fixes**:
Fixes #328 

**Special notes for your reviewer**:

**Release note**:

```other operator
The Refresh method resets the priority annotation on machines with priority 1 to match the desired count. Refer to the PR for details on how the desired count is calculated.
```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 1]
```diff
@@ -402,9 +402,52 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
...
-	return nil
+	machineDeployments, err := m.machineDeploymentLister.MachineDeployments(m.namespace).List(labels.Everything())
+	if err != nil {
+		klog.Errorf("[Refresh] unable to list machine deployments")
+		return err
+	}
+	var collectiveError error
+	for _, machineDeployment := range machineDeployments {
+		// ignore the machine deployment if it is in rolling update
+		if !isRollingUpdateFinished(machineDeployment) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:415]: What happens when a machine deployment is paused/frozen?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 2]
```diff
@@ -402,9 +402,52 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
...
+			collectiveError = errors.Join(collectiveError, err)
+			continue
+		}
+		var annotatedMachines []*v1alpha1.Machine
+		for _, machine := range machines {
+			// no need to reset priority for machines already in termination or failed phase
+			if machine.Status.CurrentStatus.Phase == v1alpha1.MachineTerminating || machine.Status.CurrentStatus.Phase == v1alpha1.MachineFailed {
+				continue
+			}
+			if machine.Annotations != nil && machine.Annotations[machinePriorityAnnotation] != defaultPriorityValue {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Instead use:
```go
	if machine.Annotations != nil && machine.Annotations[machinePriorityAnnotation] == 1 {
				annotatedMachines = append(annotatedMachines, machine)
	}
```
And maybe you can create a constant for 1 to give it a semantically meaningful name.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 3]
```diff
@@ -402,9 +402,52 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
...
+		}
+		replicas := machineDeployment.Spec.Replicas
+		// check if number of annotated machine objects is more than desired and correspondingly reset the priority annotation value if needed.
+		machines, err := m.getMachinesForMachineDeployment(machineDeployment.Name)
+		if err != nil {
+			klog.Errorf("[Refresh] failed to get machines for machine deployment %s, hence skipping it. Err: %v", machineDeployment.Name, err.Error())
+			collectiveError = errors.Join(collectiveError, err)
+			continue
+		}
+		var annotatedMachines []*v1alpha1.Machine
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: can you instead use `machinesMarkedForDeletion` instead of `annotatedMachines`?

**Review by unmarshall — CHANGES_REQUESTED** [review]

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 2 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Please use `annotVal, ok := machine.Annotations[machinePriorityAnnotation]` in map to avoid possible panic.

**Review by unmarshall — APPROVED** [review]
/lgtm
