### PR TITLE
Fix Race conditions in Targeted Deletion of machines by CA

### LINKED ISSUE #342: CA Issues invalid scale downs due to scale-down processing delay in the MCM
**What happened**:

CA requested an undesired additional reduction of the MCM `MachineDeployment` deployment while the first request to remove the machine was still in processing. This occurred due to api-server timeouts.

*Example log*

As shown below, the machine set was scaled down at `21:40:04` but till `21:40:38` it was not processed due to client-side throttling

```
2024-12-14 21:40:03 | {"log":"Processing the machinedeployment \"shoot--hc-eu10--prod-haas-edge-g-z3\" (with replicas 3)","pid":"1","severity":"INFO","source":"deployment.go:433"}
  |   | 2024-12-14 21:40:03 | {"log":"Desired replicas annotation value: 6 on machineSet shoot--hc-eu10--prod-haas-edge-g-z3-85b5b, Spec Desired Replicas value: 3 on corresponding machineDeployment, so scaling has happened.","pid":"1","severity":"INFO","source":"deployment_sync.go:693"}
  |   | 2024-12-14 21:40:03 | {"log":"Scaling detected for machineDeployment shoot--hc-eu10--prod-haas-edge-g-z3","pid":"1","severity":"INFO","source":"deployment.go:533"}
  |   | 2024-12-14 21:40:03 | {"log":"Scaling latest/theOnlyActive machineSet shoot--hc-eu10--prod-haas-edge-g-z3-85b5b","pid":"1","severity":"INFO","source":"deployment_sync.go:412"}
2024-12-14 21:40:04 | {"log":"Waited for 980.323975ms due to client-side throttling, not priority and fairness, request: PUT:https://api.aws-eu2.garden.internal.live.k8s.ondemand.com:443/apis/machine.sapcloud.io/v1alpha1/namespaces/shoot--hc-eu10--prod-haas/machinesets/shoot--hc-eu10--prod-haas-edge-g-z3-85b5b?timeout=1m0s","pid":"1","severity":"INFO","source":"request.go:632"}
  |   | 2024-12-14 21:40:04 | {"log":"shoot--hc-eu10--prod-haas-edge-g-z3-85b5b updated. Desired machine count change: 6-\u003e3","pid":"1","severity":"INFO","source":"machineset.go:155"}
  |   | 2024-12-14 21:40:04 | {"log":"Event(v1.ObjectReference{Kind:\"MachineDeployment\", Namespace:\"shoot--hc-eu10--prod-haas\", Name:\"shoot--hc-eu10--prod-haas-edge-g-z3\", UID:\"e537417f-4659-4f95-80fe-5bc448a5992e\", APIVersion:\"machine.sapcloud.io/v1alpha1\", ResourceVersion:\"54387612340\", FieldPath:\"\"}): type: 'Normal' reason: 'ScalingMachineSet' Scaled down machine set shoot--hc-eu10--prod-haas-edge-g-z3-85b5b to 3","pid":"1","severity":"INFO","source":"event.go:377"}
```
During this time, CA again requested to delete the nodes, which caused another scale-down.

```
2024-12-14 21:40:38 | {"log":"Processing the machineset \"shoot--hc-eu10--prod-haas-edge-g-z3-85b5b\" with replicas 0 associated with machine class: \"\"","pid":"1","severity":"INFO","source":"machineset.go:501"}
```

**What you expected to happen**:

CA scale down should be idempotent and should only occur once regardless of any timeouts or throttling. There should be no further reduction of replications by the CA just because MCM is delayed or there are problems executing the scale down.

**How to reproduce it (as minimally and precisely as possible)**:

 Hang the scale down in the MCM with artificial extended delay so that the CA issues erroneous scaledowns in subsequent processing cycles

### PR DESCRIPTION
**Pull request by rishabh-11**
**What this PR does / why we need it**:
This PR fixes the issues noticed in live issues 6120 and 6101. We introduce a mutex in the `NodeGroupImpl` struct (node group implementation) which must be acquired before performing a scale-down or scale-up operation. 

We also introduce an annotation on the MachineDeployment `TriggerDeletionByMCM = "node.machine.sapcloud.io/trigger-deletion-by-mcm"` whose value denotes the machines CA wants to remove and then atomically update replica count and annotation as one single step. This will help recognize machines for which CA has already reduced the replicas of the `MachineDeployment` and prevent it from being duplicated -  race conditions are avoided when CA scaledowns are occurring in parallel. The MCM is also updated to check this `TriggerDeletionByMCM` annotation on the `MachineDeployment`. 

The CA no longer directly sets the `MachinePriority=1` annotation on the `Machine` objects. This is now done by the MCM controller when reconciling the updated `MachineDeployment`.

**Which issue(s) this PR fixes**:
Fixes #342

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fix for data-races in concurrent CA scaledowns and CA restarts
```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 1]
```diff
@@ -380,6 +366,54 @@ func (machinedeployment *MachineDeployment) DecreaseTargetSize(delta int) error
...
+	mcd, err := machineDeployment.mcmManager.machineDeploymentLister.MachineDeployments(machineDeployment.Namespace).Get(machineDeployment.Name)
+	if err != nil {
+		return fmt.Errorf("failed to get machine deployment %s: %v", machineDeployment.Name, err)
+	}
+	// ignore the machine deployment if it is in rolling update
+	if !isRollingUpdateFinished(mcd) {
+		klog.Infof("machine deployment %s is under rolling update, skipping", machineDeployment.Name)
+		return nil
+	}
+	markedMachines := sets.New(strings.Split(mcd.Annotations[machinesMarkedByCAForDeletion], ",")...)
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Please move this to a small function `mcm.getMachinesMarkedByCAForDeletion(mcd) (machineNames sets.Set[string])` which is unit testable and can be consumed by both the `mcm_cloud_provider.go` and `mcm_manager.go`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 2]
```diff
@@ -380,6 +366,54 @@ func (machinedeployment *MachineDeployment) DecreaseTargetSize(delta int) error
...
+	machines, err := machineDeployment.mcmManager.getMachinesForMachineDeployment(machineDeployment.Name)
+	if err != nil {
+		klog.Errorf("[Refresh] failed to get machines for machine deployment %s, hence skipping it. Err: %v", machineDeployment.Name, err.Error())
+		return err
+	}
+	var incorrectlyMarkedMachines []*Ref
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: I believe we can omit the `Ref` struct and just used `types.NamespacedName` which is already being used anyways in this file

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 3]
```diff
@@ -539,12 +567,17 @@ func buildMachineDeploymentFromSpec(value string, mcmManager *McmManager) (*Mach
 	return machinedeployment, nil
 }
 
+func getMachinesMarkedByCAForDeletion(mcd *v1alpha1.MachineDeployment) sets.Set[string] {
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Perhaps using the "comma, ok" idiom here for `mcd.Annotations[machinesMarkedByCAForDeletion]` would be good  for clarity to avoid unnecessary split of empty string.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 4]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+	if err != nil {
+		return fmt.Errorf("failed to get machine deployment %s: %v", machineDeployment.Name, err)
 	}
-	return machinedeployment.mcmManager.retry(func(ctx context.Context) (bool, error) {
-		return machinedeployment.mcmManager.SetMachineDeploymentSize(ctx, machinedeployment, int64(decreaseAmount))
-	}, "MachineDeployment", "update", machinedeployment.Name)
+	// ignore the machine deployment if it is in rolling update
+	if !isRollingUpdateFinished(mcd) {
+		klog.Infof("machine deployment %s is under rolling update, skipping", machineDeployment.Name)
+		return nil
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:341]: Shouldn't we return an `error` here ? We are doing it for other cases of `!isRollingUpdateFinished`.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 5]
```diff
@@ -283,6 +292,23 @@ func createMCMManagerInternal(discoveryOpts cloudprovider.NodeGroupDiscoveryOpti
 	return nil, fmt.Errorf("Unable to start cloud provider MCM for cluster autoscaler: API GroupVersion %q or %q or %q is not available; \nFound: %#v", machineGVR, machineSetGVR, machineDeploymentGVR, availableResources)
 }
 
+// addNodeGroup adds node group defined in string spec. Format:
+// minNodes:maxNodes:namespace.machineDeploymentName
+func (m *McmManager) addNodeGroup(spec string) error {
+	machineDeployment, err := buildMachineDeploymentFromSpec(spec, m)
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: `buildMachineDeploymentFromSpec` should also be moved to `mcm_manager.go`.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 3 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Isn't it allowed to read from a nil map? Only writes will cause panic, right?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 6]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+	return machineDeployment.mcmManager.retry(func(ctx context.Context) (bool, error) {
+		return machineDeployment.mcmManager.SetMachineDeploymentSize(ctx, machineDeployment, int64(decreaseAmount))
+	}, "MachineDeployment", "update", machineDeployment.Name)
+}
+
+// Refresh resets the priority annotation for the machines that are not present in machines-marked-by-ca-for-deletion annotation on the machineDeployment
+func (machineDeployment *MachineDeployment) Refresh() error {
+	machineDeployment.scalingMutex.Lock()
+	defer machineDeployment.scalingMutex.Unlock()
+	mcd, err := machineDeployment.mcmManager.machineDeploymentLister.MachineDeployments(machineDeployment.Namespace).Get(machineDeployment.Name)
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: This is repeated nearly a dozen times everywhere including common error handling: `machineDeployment.mcmManager.machineDeploymentLister.MachineDeployments(machineDeployment.Namespace).Get(machineDeployment.Name)` .  Move to a method in `mcmManager` called `GetMachineDeploymentResource` which returns a formatted error that can simply be returned, so that error message is fully consistent with all uses. we are already having methods like `mcmManager.getMachinesForMachineDeployment` so this matches the existing convention.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 4 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:341]: I think we should remove this check. Even if a machineDeployment is under rolling update, we should allow the annotation update if needed. wdyt?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 7]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+		klog.Errorf("[Refresh] failed to get machines for machine deployment %s, hence skipping it. Err: %v", machineDeployment.Name, err.Error())
+		return err
+	}
+	var incorrectlyMarkedMachines []*types.NamespacedName
+	for _, machine := range machines {
+		// no need to reset priority for machines already in termination or failed phase
+		if machine.Status.CurrentStatus.Phase == v1alpha1.MachineTerminating || machine.Status.CurrentStatus.Phase == v1alpha1.MachineFailed {
+			continue
+		}
+		if annotValue, ok := machine.Annotations[machinePriorityAnnotation]; ok && annotValue == priorityValueForCandidateMachines && !markedMachines.Has(machine.Name) {
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Out of curiosity, Why is this called `priorityValueForCandidateMachines` ? Shouldn't it be defined as `const PriorityDeletionValueForCandidateMachine = 1` ?

Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: I think we can rename it to `PriorityValueForDeletionCandidateMachine`. wdyt?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 8]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+	var updatedMarkedMachines []string
+	for machineName := range markedMachines {
+		if slices.ContainsFunc(machines, func(mc *v1alpha1.Machine) bool {
+			return mc.Name == machineName
+		}) {
+			updatedMarkedMachines = append(updatedMarkedMachines, machineName)
+		}
+	}
+	clone := mcd.DeepCopy()
+	clone.Annotations[machinesMarkedByCAForDeletion] = strings.Join(updatedMarkedMachines, ",")
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: This `strings.Join` to construct the annotation repeated elsewhere. Make a utility method called `getMarkedForDeletionAnnotationValue(machineNames []string) string`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 9]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+		klog.Infof("machine deployment %s is under rolling update, skipping", machineDeployment.Name)
+		return nil
+	}
+	markedMachines := getMachinesMarkedByCAForDeletion(mcd)
+	machines, err := machineDeployment.mcmManager.getMachinesForMachineDeployment(machineDeployment.Name)
+	if err != nil {
+		klog.Errorf("[Refresh] failed to get machines for machine deployment %s, hence skipping it. Err: %v", machineDeployment.Name, err.Error())
+		return err
+	}
+	var incorrectlyMarkedMachines []*types.NamespacedName
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: minor (need not correct): `types.NamespacedName` is a simple struct - a value object. Modern programming practices discourages use of pointers to value objects for keeping data inline for processor cache performance. Pointers should be used only for structs holding active resource (like locks/files/etc) or class/service objects.   Using a simple `[]types.NamespacedName` and using `types.NamespacedName` instead of `*types.NamespacedName` should be followed for newer code.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 7 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: we should also add a comment here to explain what we are doing so next guy making a patch doesn't scratch his head.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 3 above)
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Name function to `getMachineNamesMarkedByCAForDeletion`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 10]
```diff
@@ -508,27 +474,32 @@ func (m *McmManager) DeleteMachines(targetMachineRefs []*Ref) error {
 	if !isRollingUpdateFinished(md) {
 		return fmt.Errorf("MachineDeployment %s is under rolling update , cannot reduce replica count", commonMachineDeployment.Name)
 	}
+	markedMachines := getMachinesMarkedByCAForDeletion(md)
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: `markedMachines` -> `machineNamesMarkedByCA`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 11]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+	for _, machine := range machines {
+		// no need to reset priority for machines already in termination or failed phase
+		if machine.Status.CurrentStatus.Phase == v1alpha1.MachineTerminating || machine.Status.CurrentStatus.Phase == v1alpha1.MachineFailed {
+			continue
+		}
+		if annotValue, ok := machine.Annotations[machinePriorityAnnotation]; ok && annotValue == priorityValueForCandidateMachines && !markedMachines.Has(machine.Name) {
+			incorrectlyMarkedMachines = append(incorrectlyMarkedMachines, &types.NamespacedName{Name: machine.Name, Namespace: machine.Namespace})
+		}
+	}
+	var updatedMarkedMachines []string
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: `updatedMarkedMachines` -> `updatedMarkedMachineNames`.  Also please add a comment explaining that we do to ensure that annotation do not have non-existent machine names.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 12]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+	for machineName := range markedMachines {
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: minor: Technically, you can create `allMachineNames` and use `Set.Intersection` here - which is cheaper than nested for loop, but its OK.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 13]
```diff
@@ -377,82 +403,19 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
...
-			})
-			diff := int(replicas) - len(machines) + len(machinesMarkedForDeletion)
-			targetRefs := make([]*Ref, 0, diff)
-			for i := 0; i < min(diff, len(machinesMarkedForDeletion)); i++ {
-				targetRefs = append(targetRefs, &Ref{Name: machinesMarkedForDeletion[i].Name, Namespace: machinesMarkedForDeletion[i].Namespace})
-			}
-			collectiveError = errors.Join(collectiveError, m.resetPriorityForMachines(targetRefs))
-		}
+	for _, machineDeployment := range m.machineDeployments {
+		collectiveError = errors.Join(collectiveError, machineDeployment.Refresh())
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: non-optimal use of `errors.Join` which will create repeated struct instances. `errors.Join` creates a new error object by combining multiple errors. If used in a loop, it allocates memory each time it's called. The right usage is  first make a `var errs []error` outside the loop, append individual errors  into this slice within the loop and then use `errors.Join` outside the loop to create the final error.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 14]
```diff
@@ -508,27 +474,32 @@ func (m *McmManager) DeleteMachines(targetMachineRefs []*Ref) error {
 	if !isRollingUpdateFinished(md) {
 		return fmt.Errorf("MachineDeployment %s is under rolling update , cannot reduce replica count", commonMachineDeployment.Name)
 	}
+	markedMachines := getMachinesMarkedByCAForDeletion(md)
 	// update priorities of machines to be deleted except the ones already in termination to 1
-	scaleDownAmount, err := m.prioritizeMachinesForDeletion(targetMachineRefs)
+	machinesWithPrio1, err := m.prioritizeMachinesForDeletion(targetMachineRefs)
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: `machinesWithPrio1`->`machineNamesWithPrio1`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 3 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: `getMachinesMarkedByCAForDeletion`->`getMachineNamesMarkedByCAForDeletion`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 15]
```diff
@@ -281,152 +256,205 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+	markedMachines := getMachinesMarkedByCAForDeletion(mcd)
+	machines, err := machineDeployment.mcmManager.getMachinesForMachineDeployment(machineDeployment.Name)
+	if err != nil {
+		klog.Errorf("[Refresh] failed to get machines for machine deployment %s, hence skipping it. Err: %v", machineDeployment.Name, err.Error())
+		return err
+	}
+	var incorrectlyMarkedMachines []*types.NamespacedName
+	for _, machine := range machines {
+		// no need to reset priority for machines already in termination or failed phase
+		if machine.Status.CurrentStatus.Phase == v1alpha1.MachineTerminating || machine.Status.CurrentStatus.Phase == v1alpha1.MachineFailed {
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: we already have a utiltiy method `isMachineFailedOrTerminating` . Is that not suitable or make it suitable ?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 16]
```diff
@@ -508,27 +474,32 @@ func (m *McmManager) DeleteMachines(targetMachineRefs []*Ref) error {
...
 	if err != nil {
 		return err
 	}
+	markedMachines.Insert(machinesWithPrio1...)
 	// Trying to update the machineDeployment till the deadline
 	err = m.retry(func(ctx context.Context) (bool, error) {
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Please consider whether one of the apimachinery `wait.Poll*` utility functions can be used or whether `retry` can delete to one of the apimachinery `wait.Poll*` functions. `wait.PollUntilContextTimeout` seems suitable.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 17]
```diff
@@ -552,8 +523,9 @@ func (m *McmManager) resetPriorityForMachines(mcRefs []*Ref) error {
 }
 
 // prioritizeMachinesForDeletion prioritizes the targeted machines by updating their priority annotation to 1
-func (m *McmManager) prioritizeMachinesForDeletion(targetMachineRefs []*Ref) (int, error) {
+func (m *McmManager) prioritizeMachinesForDeletion(targetMachineRefs []*types.NamespacedName) ([]string, error) {
 	var expectedToTerminateMachineNodePairs = make(map[string]string)
+	var machinesMarkedWithPrio1 []string
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: `machinesMarkedWithPrio1` -> `prio1MarkedMachineNames`. (optionally, move this variable to a named return value on this method)

MINOR: Since you are already having a map `expectedToTerminateMachineNodePairs` which should be called `prio1MarkedMachineNodeNamePairs` , you don't need another slice. You can use Go's `maps.Keys(prio1MarkedMachineNodeNamePairs).Collect()` as return value instead of separate heap allocation for duplicate slice.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 12 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: AFAIK `k8s.io/apimachinery/pkg/util/sets` does not have an Intersection method.

Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: https://github.com/kubernetes/apimachinery/blob/v0.32.0/pkg/util/sets/set.go#L156

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 17 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: maps.Keys was introduced in go 1.23 - https://pkg.go.dev/maps@go1.22.10 does not have Keys function

Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Hmm...my bad this function was added later to the package which was newly introduced in Go 1.21

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 18]
```diff
@@ -508,27 +474,32 @@ func (m *McmManager) DeleteMachines(targetMachineRefs []*Ref) error {
...
+func (m *McmManager) resetPriorityForMachines(mcRefs []*types.NamespacedName) error {
 	var collectiveError error
 	for _, mcRef := range mcRefs {
 		machine, err := m.machineLister.Machines(m.namespace).Get(mcRef.Name)
+		if kube_errors.IsNotFound(err) {
+			klog.Warningf("Machine %s not found, skipping resetting priority annotation", mcRef.Name)
+			continue
+		}
 		if err != nil {
 			collectiveError = errors.Join(collectiveError, fmt.Errorf("unable to get Machine object %s, Error: %v", mcRef, err))
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: same point regarding `errors.Join` - should be invoked just once outside loop to avoid repeated mem alloc inside for loop.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 12 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: yes but it is not part of the apimachinery version we currently use. Anyways, we do not need sets, I have replaced them with slices.

**Comment by elankath** [comment]
@rishabh-11  thanks for PR. Added review comments. Can you make a list of all test-cases  that you can think of - including success, failures, crashes etc ? I will test them out and attach test log.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 16 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: We are using our retry since `wait.PollUntilContextTimeout` does not give logs. We were able to debug the issue thanks to these logs so I think we should still keep it

**Comment by elankath** [comment]
This PR is currently under review/testing. will update with further details later.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 19]
```diff
@@ -281,152 +254,211 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
-func (machinedeployment *MachineDeployment) MaxSize() int {
-	return machinedeployment.maxSize
+func (machineDeployment *MachineDeployment) MaxSize() int {
+	return machineDeployment.maxSize
 }
 
 // MinSize returns minimum size of the node group.
-func (machinedeployment *MachineDeployment) MinSize() int {
-	return machinedeployment.minSize
+func (machineDeployment *MachineDeployment) MinSize() int {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: it is usually a practice to use short names. In this case you can perhaps just use:
```go
func (md *MachineDeployment) MinSize {}
```
Reference: https://google.github.io/styleguide/go/decisions.html#receiver-names

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 20]
```diff
@@ -281,152 +254,211 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
 // when there is an option to just decrease the target.
-func (machinedeployment *MachineDeployment) DecreaseTargetSize(delta int) error {
-	klog.V(0).Infof("Received request to decrease target size of machine deployment %s by %d", machinedeployment.Name, delta)
+func (machineDeployment *MachineDeployment) DecreaseTargetSize(delta int) error {
+	klog.V(0).Infof("Received request to decrease target size of machine deployment %s by %d", machineDeployment.Name, delta)
 	if delta >= 0 {
 		return fmt.Errorf("size decrease size must be negative")
 	}
-	size, err := machinedeployment.mcmManager.GetMachineDeploymentSize(machinedeployment)
+	machineDeployment.scalingMutex.Lock()
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: When i looked at the code, this method is called from `fixNodeGroupSize` which in our fork is not getting called from anywhere. So having a mutex here is kind of useless, right? So while the issue stated that the issue is with duplicate scale down. I am unable to relate this code change with the actual issue.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 21]
```diff
@@ -281,152 +254,211 @@ func ReferenceFromProviderID(m *McmManager, id string) (*Ref, error) {
...
+		decreaseAmount = machineDeployment.minSize
+	}
+	return machineDeployment.mcmManager.retry(func(ctx context.Context) (bool, error) {
+		return machineDeployment.mcmManager.SetMachineDeploymentSize(ctx, machineDeployment, int64(decreaseAmount))
+	}, "MachineDeployment", "update", machineDeployment.Name)
+}
+
+// Refresh resets the priority annotation for the machines that are not present in machines-marked-by-ca-for-deletion annotation on the machineDeployment
+func (machineDeployment *MachineDeployment) Refresh() error {
+	machineDeployment.scalingMutex.Lock()
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: why should a scaling mutex be used in `Refresh`?
Scaling mutex by its very name signifies mutex meant to be taken for any scaling event and not when its trying to read/get machine deployments.

Also can this result in the next reconcile of `RunOnce` to be stuck because it cannot go beyond `CloudProvider.Refresh` call?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 22]
```diff
@@ -592,28 +579,22 @@ func (m *McmManager) updateAnnotationOnMachine(ctx context.Context, mcName strin
...
 	}
 	return true, err
 }
 
-// scaleDownMachineDeployment scales down the machine deployment by the provided scaleDownAmount and returns the updated spec.Replicas after scale down.
-func (m *McmManager) scaleDownMachineDeployment(ctx context.Context, mdName string, scaleDownAmount int) (bool, error) {
-	md, err := m.machineDeploymentLister.MachineDeployments(m.namespace).Get(mdName)
+// scaleDownAndAnnotateMachineDeployment scales down the machine deployment by the provided scaleDownAmount and returns the updated spec.Replicas after scale down.
+// It also updates the machines-marked-by-ca-for-deletion annotation on the machine deployment with the list of existing machines marked for deletion.
+func (m *McmManager) scaleDownAndAnnotateMachineDeployment(ctx context.Context, mdName string, scaleDownAmount int, markedMachines string) (bool, error) {
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: 1. Should lock the mutex before updating the mcd
2. There is a check in this function to skip mcd update if there is no change to the number or replicas. Ig this should also be updated to consider the annotation as well

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 23]
```diff
@@ -491,46 +463,54 @@ func (m *McmManager) SetMachineDeploymentSize(ctx context.Context, machinedeploy
...
-	scaleDownAmount, err := m.prioritizeMachinesForDeletion(targetMachineRefs)
+	machineNamesWithPrio1, err := m.prioritizeMachinesForDeletion(targetMachineRefs)
 	if err != nil {
 		return err
 	}
+	machineNamesMarkedByCA = append(machineNamesMarkedByCA, machineNamesWithPrio1...)
 	// Trying to update the machineDeployment till the deadline
 	err = m.retry(func(ctx context.Context) (bool, error) {
-		return m.scaleDownMachineDeployment(ctx, commonMachineDeployment.Name, scaleDownAmount)
+		return m.scaleDownAndAnnotateMachineDeployment(ctx, commonMachineDeployment.Name, len(machineNamesWithPrio1), createMachinesMarkedForDeletionAnnotationValue(machineNamesMarkedByCA))
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Right now we make one call to KAPI to update the priorities and another call to change the replicas + add scale down annotation. Why can't these two be combined to reduce the number of calls to KAPI and further reduce the complexity of handling failure cases between the two calls?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 24]
```diff
@@ -98,6 +100,9 @@ const (
 	machineDeploymentPausedReason = "DeploymentPaused"
 	// machineDeploymentNameLabel key for Machine Deployment name in machine labels
 	machineDeploymentNameLabel = "name"
+	// machinesMarkedByCAForDeletion is the annotation set by CA on machine deployment. Its value denotes the machines that
+	// CA marked for deletion by updating the priority annotation to 1 and scaling down the machine deployment.
+	machinesMarkedByCAForDeletion = "cluster-autoscaler.kubernetes.io/machines-marked-by-ca-for-deletion"
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]:
```suggestion
	machinesMarkedByCAForDeletionAnnotation = "cluster-autoscaler.kubernetes.io/machines-marked-by-ca-for-deletion"
```
Need not be considered, but this is usually how annotations are defined

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 25]
```diff
@@ -377,84 +413,21 @@ func (m *McmManager) GetMachineDeploymentForMachine(machine *Ref) (*MachineDeplo
...
-		m,
-		min,
-		max,
-	}, nil
+	return machineDeployment, nil
 }
 
 // Refresh method, for each machine deployment, will reset the priority of the machines if the number of annotated machines is more than desired.
 // It will select the machines to reset the priority based on the descending order of creation timestamp.
 func (m *McmManager) Refresh() error {
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:442]: Docstring should be updated to be more accurate

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 26]
```diff
@@ -916,6 +899,16 @@ func (m *McmManager) GetMachineDeploymentNodeTemplate(machinedeployment *Machine
 	return nodeTmpl, nil
 }
 
+// GetMachineDeploymentResource returns the MachineDeployment object for the provided machine deployment name
+func (m *McmManager) GetMachineDeploymentResource(mdName string) (*v1alpha1.MachineDeployment, error) {
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]:
```suggestion
func (m *McmManager) GetMachineDeploymentObject(mdName string) (*v1alpha1.MachineDeployment, error) {
```
Ig `Object` is more accurate then `Resource`?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 19 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Yes, I actually mentioned this to rishabh that our `machineDeployment` receiver and variable names and CA nodeimpl struct names are all overloaded. But he wanted to minimize the changes. I will make this change anyways.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 21 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: We need a mutex when running scaling operations or modifying attributes that directly affect the scaling operation like the newly introduced annotation. There is not any doubt about this as we HAVE to prevent concurrent scaleups and scsledowns due to the fact that our MCM scaling is async and that multiple Go routines can perform scale downs, leading to non-deterministic behaviour.

You have a point that `RunOnce` should return an error and not block if the mutex is already acquired. Will change the code to check if mutex is acquired and if so return an informative error. Will also test this change.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 20 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: It is put in there for safety - if we are scaling in any manner we should take the mutex to free us from future CA concurrency changes.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 21 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Modified to take a `TryLock` in `NodeGroupImpl.Refresh()`. This is also a limited fix since it will block CA from changing other NodeGroups but won't block go-routines. I don't see any better way with current CA architecture. One possible improvement is to introduce a mutex with a timeout.  If you find a better way, please let me know.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 23 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: These are calls to different objects. `machinePriorityAnnotation` `machinepriority.machine.sapcloud.io`  is set on `Machine` object. And `machinesMarkedByCAForDeletion` (`cluster-autoscaler.kubernetes.io/machines-marked-by-ca-for-deletion"`) is set on the `MachineDeployment`.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 22 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: sorry for delay. `scaleDownAndAnnotateMachineDeployment` is a newly introduced private methold.  It is a helper method used by delete machines. The expectation is that callers should take the mutex. Added to godoc. I didn't get point 2)

**Comment by elankath** [comment]
UPDATE: Testing has shown that the current fix in this PR has a tendency to slow down the CA scaling due to the all the `NodeGroup` mutexes acquired in `CloudProvider.Refresh`.  We are looking whether this is acceptable or whether we can improve this.

**Comment by elankath** [comment]
Testing has revealed that the current fix unfortunately does not address all data races and also slows down the performance due to the multiple `NodeGroup` locks needed in the `CloudProvider.Refresh`. 

It has been determined we cannot achieve this as a CA-cloudprovider isolated fix and we need to make MCM changes too to ensure that scaledown works correctly even in cases where CA issues concurrent scaledowns for a NodeGroup and  changes its mind later about which node to scale down in a future iteration.

**Comment by elankath** [comment]
# Example Test Log For Scale-Down


### CA Launch Args

```
--cloud-provider=mcm --stderrthreshold=info --v=4 --max-node-provision-time=20m0s --skip-nodes-with-system-pods=false --skip-nodes-with-local-storage=false --expendable-pods-priority-cutoff=-10 --ignore-daemonsets-utilization=false --balance-similar-node-groups=true --nodes=1:5:shoot--i034796--aw.shoot--i034796--aw-a-z1 --nodes=0:5:shoot--i034796--aw.shoot--i034796--aw-b-z1 --nodes=0:5:shoot--i034796--aw.shoot--i034796--aw-c-z1 --leader-elect=false --scale-down-utilization-threshold=0.5 --max-graceful-termination-sec=600 --scale-down-unneeded-time=10s --scale-down-delay-after-add=10s --scale-down-delay-after-delete=2s --scale-down-delay-after-failure=5s --new-pod-scale-up-delay=0s --max-nodes-total=4096
```



### Initial State



```
k patch mcd shoot--i034796--aw-a-z1 --type='merge' -p '{"spec": {"replicas": 3}}' #AIncReplicas
k patch mcd shoot--i034796--aw-c-z1 --type='merge' -p '{"spec": {"replicas": 1}}' #CIncReplicas

k get mcd; k get mc; k get no; #gdmn                                                         

NAME                      READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-a-z1   3       3         3            3           56s
shoot--i034796--aw-b-z1                                              56s
shoot--i034796--aw-c-z1   1       1         1            1           56s
NAME                                  STATUS    AGE   NODE
shoot--i034796--aw-a-z1-6d674-r9gxh   Running   18s   shoot--i034796--aw-a-z1-6d674-r9gxh
shoot--i034796--aw-a-z1-6d674-sbfrt   Running   38s   shoot--i034796--aw-a-z1-6d674-sbfrt
shoot--i034796--aw-a-z1-6d674-vp87w   Running   18s   shoot--i034796--aw-a-z1-6d674-vp87w
shoot--i034796--aw-c-z1-57674-7tnrr   Running   38s   shoot--i034796--aw-c-z1-57674-7tnrr
NAME                                  STATUS   ROLES    AGE   VERSION
shoot--i034796--aw-a-z1-6d674-r9gxh   Ready    <none>   13s
shoot--i034796--aw-a-z1-6d674-sbfrt   Ready    <none>   33s
shoot--i034796--aw-a-z1-6d674-vp87w   Ready    <none>   13s
shoot--i034796--aw-c-z1-57674-7tnrr   Ready    <none>   33s

```
### CA Scaledown Log

```
grep -i shoot--i034796--aw-a-z1  /tmp/ca.log


I0130 22:23:04.039959   36186 eligibility.go:167] Node shoot--i034796--aw-a-z1-6d674-r9gxh is underutilized: memory requested (0% of allocatable) is below the scale-down utilization threshold
I0130 22:23:04.040011   36186 eligibility.go:167] Node shoot--i034796--aw-a-z1-6d674-sbfrt is underutilized: memory requested (0% of allocatable) is below the scale-down utilization threshold

I0130 22:23:04.040218   36186 nodes.go:126] shoot--i034796--aw-a-z1-6d674-r9gxh was unneeded for 0s
I0130 22:23:04.040229   36186 nodes.go:126] shoot--i034796--aw-a-z1-6d674-sbfrt was unneeded for 0s

I0130 22:23:04.049356   36186 taints.go:217] Successfully added DeletionCandidateOfClusterAutoscaler on node shoot--i034796--aw-a-z1-6d674-r9gxh
I0130 22:23:04.064233   36186 taints.go:217] Successfully added DeletionCandidateOfClusterAutoscaler on node shoot--i034796--aw-a-z1-6d674-sbfrt

I0130 22:23:14.097500   36186 taints.go:217] Successfully added ToBeDeletedByClusterAutoscaler on node shoot--i034796--aw-a-z1-6d674-r9gxh
I0130 22:23:14.109135   36186 taints.go:217] Successfully added ToBeDeletedByClusterAutoscaler on node shoot--i034796--aw-a-z1-6d674-sbfrt
I0130 22:23:14.116223   36186 actuator.go:147] Scale-down: removing empty node "shoot--i034796--aw-a-z1-6d674-r9gxh"
I0130 22:23:14.116310   36186 actuator.go:147] Scale-down: removing empty node "shoot--i034796--aw-a-z1-6d674-sbfrt"
I0130 22:23:19.117901   36186 drain.go:131] All pods removed from shoot--i034796--aw-a-z1-6d674-r9gxh
I0130 22:23:19.117884   36186 drain.go:131] All pods removed from shoot--i034796--aw-a-z1-6d674-sbfrt


I0130 22:23:19.117976   36186 mcm_cloud_provider.go:384] for NodeGroup "shoot--i034796--aw-a-z1", Received request to delete nodes:- [shoot--i034796--aw-a-z1-6d674-sbfrt]
I0130 22:23:19.117979   36186 mcm_cloud_provider.go:384] for NodeGroup "shoot--i034796--aw-a-z1", Received request to delete nodes:- [shoot--i034796--aw-a-z1-6d674-r9gxh]


I0130 22:23:19.117976   36186 mcm_cloud_provider.go:384] for NodeGroup "shoot--i034796--aw-a-z1", Received request to delete nodes:- [shoot--i034796--aw-a-z1-6d674-sbfrt]

I0130 22:23:19.117979   36186 mcm_cloud_provider.go:384] for NodeGroup "shoot--i034796--aw-a-z1", Received request to delete nodes:- [shoot--i034796--aw-a-z1-6d674-r9gxh]

I0130 22:23:19.118019   36186 mcm_cloud_provider.go:451] deleteMachines for ["shoot--i034796--aw-a-z1-6d674-sbfrt"] has acquired scalingMutex of NodeGroup "shoot--i034796--aw-a-z1"
I0130 22:23:19.147221   36186 mcm_manager.go:528] MachineDeployment shoot--i034796--aw-a-z1 size decreased to 2
I0130 22:23:19.155161   36186 mcm_manager.go:972] Node "shoot--i034796--aw-a-z1-6d674-sbfrt" has been cordoned successfully
I0130 22:23:19.155174   36186 mcm_cloud_provider.go:453] deleteMachines for ["shoot--i034796--aw-a-z1-6d674-sbfrt"] is releasing scalingMutex of NodeGroup "shoot--i034796--aw-a-z1"

I0130 22:23:19.155204   36186 mcm_cloud_provider.go:451] deleteMachines for ["shoot--i034796--aw-a-z1-6d674-r9gxh"] has acquired scalingMutex of NodeGroup "shoot--i034796--aw-a-z1"
I0130 22:23:19.161807   36186 mcm_manager.go:528] MachineDeployment shoot--i034796--aw-a-z1 size decreased to 1
I0130 22:23:19.166900   36186 mcm_manager.go:972] Node "shoot--i034796--aw-a-z1-6d674-r9gxh" has been cordoned successfully
I0130 22:23:19.166918   36186 mcm_cloud_provider.go:453] deleteMachines for ["shoot--i034796--aw-a-z1-6d674-r9gxh"] is releasing scalingMutex of NodeGroup "shoot--i034796--aw-a-z1"

I0130 22:23:24.129193   36186 pre_filtering_processor.go:67] Skipping shoot--i034796--aw-a-z1-6d674-r9gxh - node group min size reached (current: 1, min: 1)



grep -i shoot--i034796--aw-c-z1 /tmp/ca.log

I0130 22:23:14.116349   36186 actuator.go:147] Scale-down: removing empty node "shoot--i034796--aw-c-z1-57674-7tnrr"
I0130 22:23:19.117882   36186 drain.go:131] All pods removed from shoot--i034796--aw-c-z1-57674-7tnrr
I0130 22:23:19.117975   36186 mcm_cloud_provider.go:384] for NodeGroup "shoot--i034796--aw-c-z1", Received request to delete nodes:- [shoot--i034796--aw-c-z1-57674-7tnrr]
I0130 22:23:19.118026   36186 mcm_cloud_provider.go:451] deleteMachines for ["shoot--i034796--aw-c-z1-57674-7tnrr"] has acquired scalingMutex of NodeGroup "shoot--i034796--aw-c-z1"
I0130 22:23:19.147192   36186 mcm_manager.go:528] MachineDeployment shoot--i034796--aw-c-z1 size decreased to 0
I0130 22:23:19.154755   36186 mcm_manager.go:972] Node "shoot--i034796--aw-c-z1-57674-7tnrr" has been cordoned successfully
I0130 22:23:19.154815   36186 mcm_cloud_provider.go:453] deleteMachines for ["shoot--i034796--aw-c-z1-57674-7tnrr"] is releasing scalingMutex of NodeGroup "shoot--i034796--aw-c-z1"
I0130 22:23:24.129185   36186 pre_filtering_processor.go:67] Skipping shoot--i034796--aw-c-z1-57674-7tnrr - node group min size reached (current: 0, min: 0)


```


## State After CA Scaledown and BEFORE MCM Deletion


```

NAME                      READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-a-z1   3       1         3            3           4m56s
shoot--i034796--aw-b-z1                                              4m56s
shoot--i034796--aw-c-z1   1                 1            1           4m56s
NAME                                  STATUS    AGE     NODE
shoot--i034796--aw-a-z1-6d674-r9gxh   Running   4m19s   shoot--i034796--aw-a-z1-6d674-r9gxh
shoot--i034796--aw-a-z1-6d674-sbfrt   Running   4m39s   shoot--i034796--aw-a-z1-6d674-sbfrt
shoot--i034796--aw-a-z1-6d674-vp87w   Running   4m19s   shoot--i034796--aw-a-z1-6d674-vp87w
shoot--i034796--aw-c-z1-57674-7tnrr   Running   4m39s   shoot--i034796--aw-c-z1-57674-7tnrr
NAME                                  STATUS                     ROLES    AGE     VERSION
shoot--i034796--aw-a-z1-6d674-r9gxh   Ready,SchedulingDisabled   <none>   4m14s
shoot--i034796--aw-a-z1-6d674-sbfrt   Ready,SchedulingDisabled   <none>   4m34s
shoot--i034796--aw-a-z1-6d674-vp87w   Ready                      <none>   4m14s
shoot--i034796--aw-c-z1-57674-7tnrr   Ready,SchedulingDisabled   <none>   4m34s


k get mcd shoot--i034796--aw-a-z1 -oyaml | grep -i trigger                                             
    node.machine.sapcloud.io/trigger-deletion-by-mcm: shoot--i034796--aw-a-z1-6d674-r9gxh,shoot--i034796--aw-a-z1-6d674-sbfrt


k get mcd shoot--i034796--aw-c-z1 -oyaml | grep -i trigger                                            
    node.machine.sapcloud.io/trigger-deletion-by-mcm: shoot--i034796--aw-c-z1-57674-7tnrr
```

```

```


## State AFTER MCM Machine Deletion


### MCM Deletion Log

```
I0130 22:31:23.251913   35570 machineset_util.go:217] Machine "shoot--i034796--aw-c-z1-57674-7tnrr" needs to be deleted
I0130 22:31:44.289612   35570 machineset_util.go:217] Machine "shoot--i034796--aw-a-z1-6d674-sbfrt" needs to be deleted
I0130 22:31:44.289633   35570 machineset_util.go:217] Machine "shoot--i034796--aw-a-z1-6d674-r9gxh" needs to be deleted
```


### Final State

```
NAME                      READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-a-z1   1       1         1            1           14m
shoot--i034796--aw-b-z1                                              14m
shoot--i034796--aw-c-z1                                              14m
NAME                                  STATUS    AGE   NODE
shoot--i034796--aw-a-z1-6d674-vp87w   Running   13m   shoot--i034796--aw-a-z1-6d674-vp87w
NAME                                  STATUS   ROLES    AGE   VERSION
shoot--i034796--aw-a-z1-6d674-vp87w   Ready    <none>   13m
```

**Comment by elankath** [comment]
# Example Test Log For Scale-Up


## Scale up Verification

### Initial State

```
k get mcd; k get mc; k get no; #gdmn                                                         
NAME                      READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-a-z1   1       1         1            1           38m
shoot--i034796--aw-b-z1                                              38m
shoot--i034796--aw-c-z1                                              38m
NAME                                  STATUS    AGE     NODE
shoot--i034796--aw-a-z1-6d674-sl6fj   Running   5m40s   shoot--i034796--aw-a-z1-6d674-sl6fj
NAME                                  STATUS   ROLES    AGE     VERSION
shoot--i034796--aw-a-z1-6d674-sl6fj   Ready    <none>   5m35s
(⎈|default-context:shoot--i034796--aw)machine-controller-manager-provider-virtual ➤ k get po -owide                                                                              
NAME      READY   STATUS    RESTARTS   AGE   IP       NODE                                  NOMINATED NODE   READINESS GATES
a-6cjs5   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-6lr5j   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-75ztf   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-bspr8   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-dc4xz   0/1     Pending   0          87s   <none>   shoot--i034796--aw-a-z1-6d674-sl6fj   <none>           <none>
a-j2gmh   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-pkvzd   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-pzffw   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-qqph5   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
a-s6phx   0/1     Pending   0          87s   <none>   <none>                                <none>           <none>
c-8kz44   0/1     Pending   0          8s    <none>   <none>                                <none>           <none>
c-dfck5   0/1     Pending   0          8s    <none>   <none>                                <none>           <none>
```

### CA Scaleup Log


```
➤ grep -i shoot--i034796--aw-a-z1 /tmp/ca.log

I0130 22:58:36.322947   39926 orchestrator.go:184] Best option to resize: shoot--i034796--aw-c-z1
I0130 22:58:36.322958   39926 orchestrator.go:188] Estimated 2 nodes needed in shoot--i034796--aw-c-z1
I0130 22:58:36.323001   39926 compare_nodegroups.go:164] nodes template-node-for-shoot--i034796--aw-c-z1-8104371275252314947 and template-node-for-shoot--i034796--aw-b-z1-5115723038795357729 are not similar, cpu does not match
I0130 22:58:36.323045   39926 compare_nodegroups.go:164] nodes template-node-for-shoot--i034796--aw-c-z1-8104371275252314947 and template-node-for-shoot--i034796--aw-a-z1-7390413460911037548 are not similar, cpu does not match
I0130 22:58:36.323090   39926 orchestrator.go:257] Final scale-up plan: [{shoot--i034796--aw-c-z1 0->2 (max: 5)}]
I0130 22:58:36.323122   39926 executor.go:147] Scale-up: setting group shoot--i034796--aw-c-z1 size to 2
I0130 22:58:36.323198   39926 mcm_cloud_provider.go:283] Received request to increase size of machine deployment shoot--i034796--aw-c-z1 by 2
I0130 22:58:36.323211   39926 mcm_cloud_provider.go:451] IncreaseSize by #2 has acquired scalingMutex of NodeGroup "shoot--i034796--aw-c-z1"
I0130 22:58:36.337546   39926 mcm_cloud_provider.go:453] IncreaseSize by #2 is releasing scalingMutex of NodeGroup "shoot--i034796--aw-c-z1"

 ➤ grep -i shoot--i034796--aw-b-z1 /tmp/ca.log

I0130 22:58:46.350818   39926 orchestrator.go:257] Final scale-up plan: [{shoot--i034796--aw-b-z1 0->1 (max: 5)}]
I0130 22:58:46.350860   39926 executor.go:147] Scale-up: setting group shoot--i034796--aw-b-z1 size to 1
I0130 22:58:46.350922   39926 mcm_cloud_provider.go:283] Received request to increase size of machine deployment shoot--i034796--aw-b-z1 by 1
I0130 22:58:46.350934   39926 mcm_cloud_provider.go:451] IncreaseSize by #1 has acquired scalingMutex of NodeGroup "shoot--i034796--aw-b-z1"
I0130 22:58:46.363196   39926 mcm_cloud_provider.go:453] IncreaseSize by #1 is releasing scalingMutex of NodeGroup "shoot--i034796--aw-b-z1"
```

### State After CA Scaleup


```
k get mcd; k get mc; k get no; #gdmn                                                         
NAME                      READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-a-z1   1       1         1            1           39m
shoot--i034796--aw-b-z1   1       1         1            1           39m
shoot--i034796--aw-c-z1   2       2         2            2           39m
NAME                                  STATUS    AGE     NODE
shoot--i034796--aw-a-z1-6d674-sl6fj   Running   6m45s   shoot--i034796--aw-a-z1-6d674-sl6fj
shoot--i034796--aw-b-z1-855cb-8rgc7   Running   53s     shoot--i034796--aw-b-z1-855cb-8rgc7
shoot--i034796--aw-c-z1-57674-97w46   Running   63s     shoot--i034796--aw-c-z1-57674-97w46
shoot--i034796--aw-c-z1-57674-lz24s   Running   63s     shoot--i034796--aw-c-z1-57674-lz24s
NAME                                  STATUS   ROLES    AGE     VERSION
shoot--i034796--aw-a-z1-6d674-sl6fj   Ready    <none>   6m41s
shoot--i034796--aw-b-z1-855cb-8rgc7   Ready    <none>   49s
shoot--i034796--aw-c-z1-57674-97w46   Ready    <none>   54s
shoot--i034796--aw-c-z1-57674-lz24s   Ready    <none>   59s
(⎈|default-context:shoot--i034796--aw)machine-controller-manager-provider-virtual ➤ k get po -owide                                                                             
NAME      READY   STATUS    RESTARTS   AGE     IP       NODE                                  NOMINATED NODE   READINESS GATES
a-6cjs5   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
a-6lr5j   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
a-75ztf   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
a-bspr8   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
a-dc4xz   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-a-z1-6d674-sl6fj   <none>           <none>
a-j2gmh   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-97w46   <none>           <none>
a-pkvzd   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
a-pzffw   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-97w46   <none>           <none>
a-qqph5   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
a-s6phx   0/1     Running   0          2m31s   <none>   shoot--i034796--aw-c-z1-57674-lz24s   <none>           <none>
c-8kz44   0/1     Running   0          72s     <none>   shoot--i034796--aw-b-z1-855cb-8rgc7   <none>           <none>
c-dfck5   0/1     Running   0          72s     <none>   shoot--i034796--aw-c-z1-57674-97w46   <none>           <none>
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 27]
```diff
@@ -1032,6 +943,78 @@ func (m *McmManager) buildNodeFromTemplate(name string, template *nodeTemplate)
...
+		klog.V(3).Infof("Node %q has been cordoned successfully", nodeName)
+	}
+	if len(errs) > 0 {
+		return utilerrors.NewAggregate(errs)
+	}
+	return nil
+}
+
+// GetMachineInfo extracts the machine Key from the given node's providerID if found and checks whether it is failed or terminating and returns the MachineInfo or an error
+func (m *McmManager) GetMachineInfo(node *apiv1.Node) (*machineInfo, error) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Usually it is not a good practice to return non-exposed types from an exported method in golang.
Even the Goland IDE will highlight this.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 28]
```diff
@@ -1032,6 +943,78 @@ func (m *McmManager) buildNodeFromTemplate(name string, template *nodeTemplate)
...
+		return nil, fmt.Errorf("cannot list machines in namespace %q due to: %s", m.namespace, err)
+	}
+
+	providerID := node.Spec.ProviderID
+	var machineName, machineNamespace string
+	var isFailedOrTerminating bool
+	for _, machine := range machines {
+		machineID := strings.Split(machine.Spec.ProviderID, "/")
+		nodeID := strings.Split(node.Spec.ProviderID, "/")
+		// If registered, the ID will match the cloudprovider instance ID.
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1015]: which ID is this? `machineID` or `nodeID`? Can you be a bit more precise?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 29]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
-		Name:      Name,
-		Namespace: Namespace,
-	}, nil
-}
-
-// MachineDeployment implements NodeGroup interface.
-type MachineDeployment struct {
-	Ref
+// NodeGroupImpl implements NodeGroup interface.
+type NodeGroupImpl struct {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: why can't you simply name the struct `nodeGroup` - see cluster API provider. There is also no need to expose it as all the consumers are in the same golang package. I am not sure if yet if suffixing `Impl` is a golang convention.

Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Also can you add the following line:
```go
var _ cloudprovider.NodeGroup = (*nodeGroup)(nil)
```
This will ensure that all methods as defined in the `cloudprovider.NodeGroup` interface are implemented by struct type `nodeGroup`

**Comment by aaronfern** [comment]
After a discussion with @unmarshall, we still have one case where these changes will have a negative impact. It is as follows 
1. Assume our mcd has the following specs - min:3, max:5, current: 4
2. CA decides to scale down the mcd to 3. It cordons one node.
3. Before MCM acts, a user manually updated the mcd to have min:5, max:5
4. This causes the mcd to now have replicas=5
5. There are already 4 existing nodes, so MCM beings up one more node. Moreover CA is removed from the control plane since mcd.min==mac.max
6. The cordoned node still remains cordoned and will continue to stay that way until manual intervention

This is an edge case as it depends on MCM not acting and user action at the right(wrong?) time

I'm not asking this to be solved as part of this PR, but adding it here so that it is documented somewhere

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 30]
```diff
@@ -1032,6 +943,78 @@ func (m *McmManager) buildNodeFromTemplate(name string, template *nodeTemplate)
 	return &node, nil
 }
 
+func (m *McmManager) cordonNodes(nodeNames []string) error {
+	if len(nodeNames) == 0 {
+		return nil
+	}
+	if m.nodeInterface == nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: when will `nodeInterface` be nil? If it is nil then its a programming error, right? If yes, then error should be returned and not nil.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 31]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
 	if err != nil {
-		return false, err
+		return err
+	}
+	toBeDeletedMachineNames := getMachineNamesTriggeredForDeletion(mcd)
+	if len(toBeDeletedMachineNames) == 0 {
+		return nil
+	}
+	machinesOfNodeGroup, err := ngImpl.mcmManager.getMachinesForMachineDeployment(ngImpl.Name)
+	if err != nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:344]: If cordoning nodes is a best effort activity, then why return an error here? It is possible that there is nothing to cordon but this call fails and this impacts the runOnce flow of CA which is quite unnecessary, right?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 32]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+	return
 }
 
 // DeleteNodes deletes the nodes from the group. It is expected that this method will not be called
 // for nodes which are not part of ANY machine deployment.
-func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) error {
-	nodeNames := getNodeNames(nodes)
-	klog.V(0).Infof("Received request to delete nodes:- %v", nodeNames)
-	size, err := machinedeployment.mcmManager.GetMachineDeploymentSize(machinedeployment)
+func (ngImpl *NodeGroupImpl) DeleteNodes(nodes []*apiv1.Node) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: instead of `ngImpl` just use `ng` as the receiver.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 33]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+	err = ngImpl.mcmManager.cordonNodes(toBeDeletedNodeNames)
+	if err != nil {
+		// we do not return error since we don't want this to block CA operation. This is best-effort.
+		klog.Warningf("NodeGroup.Refresh() of %q ran into error cordoning nodes: %v", ngImpl.Name, err)
+	}
+	return nil
+}
+
+// Belongs checks if the given node belongs to this NodeGroup and also returns its MachineInfo for its corresponding Machine
+func (ngImpl *NodeGroupImpl) Belongs(node *apiv1.Node) (belongs bool, mInfo *machineInfo, err error) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: why is this method exported? It is not even part of clouprovider.NodeGroup interface and there is no other package that is going to use it.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 34]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+	if err != nil || mInfo == nil {
+		return
 	}
-	targetMd, err := machinedeployment.mcmManager.GetMachineDeploymentForMachine(ref)
+	targetMd, err := ngImpl.mcmManager.GetNodeGroupImpl(mInfo.Key)
 	if err != nil {
-		return false, err
+		return
 	}
 	if targetMd == nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: if the return value is `belongs bool` then why return an error?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 35]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+		// Do not return error as cordoning is best-effort
+		klog.Warningf("NodeGroup.deleteMachines() of %q ran into error cordoning nodes: %v", ngImpl.Name, err)
 	}
-	return machinedeployment.mcmManager.DeleteMachines(machines)
+	return nil
 }
 
-func getNodeNames(nodes []*apiv1.Node) interface{} {
+// AcquireScalingMutex acquires the scalingMutex associated with this NodeGroup and returns a function that releases the scalingMutex that is expected to be deferred by the caller.
+func (ngImpl *NodeGroupImpl) AcquireScalingMutex(operation string) (releaseFn func()) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: why is `AcquireScalingMutex` exported? is anyone using it outside the package?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 36]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+		nodeName := m.Labels["node"]
+		if nodeName != "" {
+			nodeNames = append(nodeNames, nodeName)
+		}
+	}
+	return nodeNames
+}
+
+// Id returns MachineDeployment id.
+func (ngImpl *NodeGroupImpl) Id() string {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: why call this method Id when it returns the Name?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 37]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+	size, err := ngImpl.mcmManager.GetMachineDeploymentSize(ngImpl.Name)
 	if err != nil {
 		return err
 	}
-	if int(size) <= machinedeployment.MinSize() {
+	if int(size) <= ngImpl.MinSize() {
 		return fmt.Errorf("min size reached, nodes will not be deleted")
 	}
-	machines := make([]*Ref, 0, len(nodes))
+	var toBeDeletedMachineInfos []machineInfo
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: it is better to set the capacity in general.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 38]
```diff
@@ -248,210 +227,269 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+	}
+	return ngImpl.deleteMachines(toBeDeletedMachineInfos)
+}
+
+// deleteMachines annotates the corresponding MachineDeployment with machine names of toBeDeletedMachineInfos, reduces the desired replicas of the corresponding MachineDeployment and cordons corresponding nodes belonging to toBeDeletedMachineInfos
+func (ngImpl *NodeGroupImpl) deleteMachines(toBeDeletedMachineInfos []machineInfo) error {
+	if len(toBeDeletedMachineInfos) == 0 {
+		return nil
+	}
+	var toBeDeletedMachineNames, toBeDeletedNodeNames []string
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: its always better to assign capacity.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 39]
```diff
@@ -592,45 +480,52 @@ func (m *McmManager) updateAnnotationOnMachine(ctx context.Context, mcName strin
...
 		return true, err
 	}
-	mdclone := md.DeepCopy()
-	expectedReplicas := mdclone.Spec.Replicas - int32(scaleDownAmount)
-	if expectedReplicas == mdclone.Spec.Replicas {
-		klog.Infof("MachineDeployment %q is already set to %d, skipping the update", mdclone.Name, expectedReplicas)
+
+	scaleDownAmount := len(toBeDeletedMachineNames)
+	expectedReplicas := md.Spec.Replicas - int32(scaleDownAmount)
+	if expectedReplicas == md.Spec.Replicas {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: instead this could have been simplified by simply checking the following:
```go
if len(toBeDeleteMachineNames) > 0 {
  // do the processing
} else {
   // log
}
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 40]
```diff
@@ -504,49 +542,51 @@ func (machinedeployment *MachineDeployment) GetOptions(defaults config.NodeGroup
...
-func buildMachineDeployment(mcmManager *McmManager, minSize int, maxSize int, namespace string, name string) *MachineDeployment {
-	return &MachineDeployment{
-		mcmManager: mcmManager,
-		minSize:    minSize,
-		maxSize:    maxSize,
-		Ref: Ref{
-			Name:      name,
-			Namespace: namespace,
-		},
+func mergeStringSlicesUnique(slice1, slice2 []string) []string {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: you could have just used `sets.Insert`

**Review by unmarshall — CHANGES_REQUESTED** [review]

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 33 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: This method was already there - I think folks just copied over method from other cloud providers where it is exported for some reason. Making it private.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 34 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: I questioned this myself, but this is what other providers also do and was the behaviour from beginning.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 41]
```diff
@@ -248,210 +229,271 @@ func (mcm *mcmCloudProvider) GetNodeGpuConfig(*apiv1.Node) *cloudprovider.GpuCon
...
+	return
 }
 
 // DeleteNodes deletes the nodes from the group. It is expected that this method will not be called
 // for nodes which are not part of ANY machine deployment.
-func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) error {
-	nodeNames := getNodeNames(nodes)
-	klog.V(0).Infof("Received request to delete nodes:- %v", nodeNames)
-	size, err := machinedeployment.mcmManager.GetMachineDeploymentSize(machinedeployment)
+func (ngImpl *nodeGroup) DeleteNodes(nodes []*apiv1.Node) error {
```
Comment (rishabh-11) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:388]: Consider multiple calls to `DeleteNodes` for the same node object `N1`. I am not able to find the place where we are making sure that this does not cause multiple scale downs. Can you please show me where we have handled this case?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 31 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:344]: corrected.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 41 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:388]: @rishabh-11  I have now separated the computation logic into `computeScaledownData` inside `mcm_manager.go` and added unit tests for duplicate and overlapping scale-downs.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 27 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: corrected. made method non-exported.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 30 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: corrected. unit tests were adjusted.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 36 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: This is legacy method in `cloudprovider.NodeGroup` - not really in our control.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 37 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: capacity is now set.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 38 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: done.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 39 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Please check new utility function: `computeScaledownData` in `mcm_manager.go` to de-couple scale-down computation from MCD update.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 40 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Removed this function

**Comment by elankath** [comment]
@rishabh-11  unfortunely PR is failing due to `license/cla` as this was originally your pull request. Can you check if re-accepting https://cla-assistant.io/gardener/autoscaler?pullRequest=341 solves it or not ?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 42]
```diff
@@ -1075,3 +1075,35 @@ func filterExtendedResources(allResources v1.ResourceList) (extendedResources v1
 	})
 	return
 }
+
+// computeScaledownData computes fresh scaleDownData for the given MachineDeployment given the machineNamesForDeletion
+func computeScaledownData(md *v1alpha1.MachineDeployment, machineNamesForDeletion []string) (data scaleDownData) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Can you rename the method to `computeScaleDownData`?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 43]
```diff
@@ -1075,3 +1075,35 @@ func filterExtendedResources(allResources v1.ResourceList) (extendedResources v1
...
+	forDeletionSet := sets.New(machineNamesForDeletion...)
+	alreadyMarkedSet := sets.New(getMachineNamesTriggeredForDeletion(md)...)
+
+	uniqueForDeletionSet := forDeletionSet.Difference(alreadyMarkedSet)
+	toBeMarkedSet := alreadyMarkedSet.Union(forDeletionSet)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1115]: if you are using sets of strings then why do you need to get a difference and then take a union later on?
You can just take the existing and insert all new ones. Sets will anyways ensure that there are no duplicates.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 44]
```diff
@@ -1075,3 +1075,35 @@ func filterExtendedResources(allResources v1.ResourceList) (extendedResources v1
...
+
+	data.RevisedToBeDeletedNames = uniqueForDeletionSet
+	data.RevisedScaledownAmount = uniqueForDeletionSet.Len()
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1118]: what is the purpose of `RevisedScaledownAmount` if its always going to be the length of `RevisedToBeDeletedNames`?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 45]
```diff
@@ -1075,3 +1075,35 @@ func filterExtendedResources(allResources v1.ResourceList) (extendedResources v1
...
+	data.RevisedMachineDeployment = nil
+
+	expectedReplicas := md.Spec.Replicas - int32(data.RevisedScaledownAmount)
+	if expectedReplicas == md.Spec.Replicas {
+		klog.Infof("MachineDeployment %q is already set to %d, no need to scale-down", md.Name, expectedReplicas)
+	} else if expectedReplicas < 0 {
+		klog.Errorf("Cannot delete machines in MachineDeployment %q, expected decrease in replicas: %d is more than current replicas: %d", md.Name, data.RevisedScaledownAmount, md.Spec.Replicas)
+	} else {
+		mdCopy := md.DeepCopy()
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1127]: is there a need to create a MachineDeployment copy and keep it in the `scaleDownData` struct?
This could have been easily done by the caller and given that there is a single caller of this method this was not really necessary.

Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1127]: Yes, I believe this is needed for computational symmetry and coalescing of responsibility. This function takes in an input `MachineDeployment`  and input parameter and returns an output parameter `scaledownData` that contains a revised `MachineDeployment`. The callers job is only to update the store and not do any construction/modification of the `MachineDeployment`. If there are further changes to the revised `MachineDeployment` it will be fully encapsulated within `computeScaleDownData`.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 43 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1115]: I don't understand - it makes no difference since `sets.Insert(slice...)` will return a new set anyways. We are using union since parameter is a set and not a slice.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 44 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:1118]: It was just for documented legibility so callers can simply use `scaleDownData.RevisedScaledownAmount`. Its just a single `int` in the output type to offer clarity in consumption and logging.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 42 above)
Comment (elankath) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: corrected.

**Comment by elankath** [comment]
## CA Integration Test Run

Integration Test Run of specs for standard scale-up, scale-down, test scale-down disabled

```
ill run 5 of 5 specs
------------------------------
[BeforeSuite] 
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:26
Scaling Cluster Autoscaler to 0 replicas
  STEP: Adjusting node groups to initial required size @ 02/05/25 01:54:25.024
  STEP: Marking nodes present before the tests as unschedulable @ 02/05/25 01:59:00.273
  STEP: Taint node ip-10-180-24-5.eu-west-1.compute.internal @ 02/05/25 01:59:00.469
  STEP: Starting Cluster Autoscaler.... @ 02/05/25 01:59:01.534
[BeforeSuite] PASSED [279.858 seconds]
------------------------------
Cluster Autoscaler test Scale up and down nodes by deploying new workload requesting more resources should not lead to any errors and add 1 more node in target cluster
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:96
  STEP: Deploying workload... @ 02/05/25 01:59:01.534
  STEP: Validating Scale up @ 02/05/25 01:59:01.731
• [104.484 seconds]
------------------------------
Cluster Autoscaler test Scale up and down nodes by scaling deployed workload to 3 replicas should not lead to any errors and add 3 more node in target cluster
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:111
  STEP: Scaling up workload to 3 replicas... @ 02/05/25 02:00:46.019
  STEP: Validating Scale up @ 02/05/25 02:00:46.403
• [106.381 seconds]
------------------------------
Cluster Autoscaler test Scale up and down nodes by scaling down the deployed workload to 0 should not lead to any errors and 3 nodes to be removed from the target cluster
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:126
  STEP: Scaling down workload to zero... @ 02/05/25 02:02:32.401
  STEP: Validating Scale down @ 02/05/25 02:02:33.192
  STEP: Deleting workload @ 02/05/25 02:03:47.252
  STEP: Checking that number of Ready nodes is equal to initial @ 02/05/25 02:03:47.444
• [75.240 seconds]
------------------------------
Cluster Autoscaler test testing annotation to skip scaledown by adding annotation and then scaling the workload to zero should not scale down the extra node and should log correspondingly
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:143
  STEP: adding the annotation after deploy workload to 1 @ 02/05/25 02:03:47.642
  STEP: Validating Scale up @ 02/05/25 02:03:47.838
  STEP: getting the latest added node and adding annotation to it. @ 02/05/25 02:05:32.014
  STEP: Scaling down workload to zero... @ 02/05/25 02:05:32.416
• [105.185 seconds]
------------------------------
Cluster Autoscaler test testing annotation to skip scaledown by adding annotation and then scaling the workload to zero Should remove the unwanted node once scale down disable annotation is removed
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:168
  STEP: getting the latest added node and removing annotation from it. @ 02/05/25 02:05:33.033
  STEP: Validating Scale down @ 02/05/25 02:05:33.431
  STEP: Deleting workload @ 02/05/25 02:06:36.89
  STEP: Checking that number of Ready nodes is equal to initial @ 02/05/25 02:06:37.098
• [64.474 seconds]
------------------------------
[AfterSuite] 
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:27
  STEP: Running CleanUp @ 02/05/25 02:06:37.302
  STEP: Deleting workload @ 02/05/25 02:06:37.302
  STEP: Adjusting node groups to initial required size @ 02/05/25 02:06:39.047
  STEP: Deleting workload @ 02/05/25 02:06:39.424
  STEP: Turning nodes present before the tests, back to schedulable @ 02/05/25 02:06:39.613
  STEP: Removing taint(s) from node ip-10-180-24-5.eu-west-1.compute.internal @ 02/05/25 02:06:39.81
  STEP: Removing taint(s) from node ip-10-180-74-58.eu-west-1.compute.internal @ 02/05/25 02:06:40.209
  STEP: Scaling CA back up to 1 in the Shoot namespace @ 02/05/25 02:06:40.629
Scaling Cluster Autoscaler to 1 replicas
[AfterSuite] PASSED [4.178 seconds]
------------------------------

Ran 5 of 5 Specs in 739.801 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (739.80s)
PASS
```

**Comment by elankath** [comment]
## CA Integration Test Run

CA Integration Test Run output for NodeGroup min-max, limits, taint-causing-scaling, etc


```
Will run 6 of 6 specs
------------------------------
[BeforeSuite] 
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:25
Scaling Cluster Autoscaler to 0 replicas
  STEP: Adjusting node groups to initial required size @ 02/05/25 02:08:30.115
  STEP: Marking nodes present before the tests as unschedulable @ 02/05/25 02:08:30.496
  STEP: Taint node ip-10-180-24-5.eu-west-1.compute.internal @ 02/05/25 02:08:30.691
  STEP: Taint node ip-10-180-74-58.eu-west-1.compute.internal @ 02/05/25 02:08:31.086
  STEP: Starting Cluster Autoscaler.... @ 02/05/25 02:08:31.832
[BeforeSuite] PASSED [5.155 seconds]
------------------------------
Cluster Autoscaler test testing min and max limit for Cluster autoscaler by increasing the workload to above max shouldn't scale beyond max number of workers
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:188
  STEP: Deploying workload with replicas = max+4 @ 02/05/25 02:08:31.833
  STEP: Validating Scale up @ 02/05/25 02:08:32.03
• [105.186 seconds]
------------------------------
Cluster Autoscaler test testing min and max limit for Cluster autoscaler by decreasing the workload to below min shouldn't scale down beyond min number of workers
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:200
  STEP: Scaling down workload to zero... @ 02/05/25 02:10:17.019
  STEP: Validating Scale down @ 02/05/25 02:10:17.403
  STEP: Deleting workload @ 02/05/25 02:11:31.516
  STEP: Checking that number of Ready nodes is equal to initial @ 02/05/25 02:11:31.709
• [74.891 seconds]
------------------------------
Cluster Autoscaler test testing scaling due to taints make current nodes unschedulable should spawn more nodes for accommodating new workload
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:216
  STEP: making the only node available, to be unschedulable @ 02/05/25 02:11:31.911
  STEP: Taint node ip-10-180-74-58.eu-west-1.compute.internal @ 02/05/25 02:11:32.102
  STEP: Increasing the workload @ 02/05/25 02:11:32.502
  STEP: Validating Scale up @ 02/05/25 02:11:32.698
• [104.870 seconds]
------------------------------
Cluster Autoscaler test testing scaling due to taints make current nodes unschedulable should remove the node as the taint has been removed and node has low utilization
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:233
  STEP: making the node available to be schedulable @ 02/05/25 02:13:16.782
  STEP: Removing taint(s) from node ip-10-180-74-58.eu-west-1.compute.internal @ 02/05/25 02:13:16.978
  STEP: Validating Scale down @ 02/05/25 02:13:17.38
  STEP: Deleting workload @ 02/05/25 02:14:20.897
  STEP: Checking that number of Ready nodes is equal to initial @ 02/05/25 02:14:21.092
• [64.509 seconds]
------------------------------
Cluster Autoscaler test testing scaling due to volume pending create a volume in a zone with no node and a pod requesting it should create a node in the zone with volume and hence scale up
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:252
  STEP: Creating StorageClass with topology restrictions @ 02/05/25 02:14:21.291
  STEP: deploying PVC in zone with no nodes @ 02/05/25 02:14:21.483
  STEP: deploying the workload which requires the volume @ 02/05/25 02:14:21.678
  STEP: Validation scale up to +1 in a new Zone @ 02/05/25 02:14:21.872
  STEP: Removing pvc created earlier @ 02/05/25 02:15:55.578
  STEP: Removing storage Class created earlier @ 02/05/25 02:15:55.771
  STEP: Deleting workload @ 02/05/25 02:15:55.964
  STEP: Checking that number of Ready nodes is equal to initial @ 02/05/25 02:15:56.165
• [158.437 seconds]
------------------------------
Cluster Autoscaler test testing not able to scale due to excess demand create a pod requiring more resources than a single machine can provide shouldn't scale up and log the error
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:320
  STEP: Deploying the workload @ 02/05/25 02:16:59.669
  STEP: checking that scale up didn't trigger because of no machine satisfying the requirement @ 02/05/25 02:16:59.866
  STEP: Deleting workload @ 02/05/25 02:17:09.911
  STEP: Checking that number of Ready nodes is equal to initial @ 02/05/25 02:17:10.119
• [10.842 seconds]
------------------------------
[AfterSuite] 
/Users/I034796/go/src/k8s.io/autoscaler/cluster-autoscaler/integration/integration_test.go:26
  STEP: Running CleanUp @ 02/05/25 02:17:10.511
  STEP: Deleting workload @ 02/05/25 02:17:10.511
  STEP: Adjusting node groups to initial required size @ 02/05/25 02:17:12.652
  STEP: Deleting workload @ 02/05/25 02:17:13.04
  STEP: Turning nodes present before the tests, back to schedulable @ 02/05/25 02:17:13.229
  STEP: Removing taint(s) from node ip-10-180-24-5.eu-west-1.compute.internal @ 02/05/25 02:17:13.432
  STEP: Removing taint(s) from node ip-10-180-74-58.eu-west-1.compute.internal @ 02/05/25 02:17:13.836
  STEP: Scaling CA back up to 1 in the Shoot namespace @ 02/05/25 02:17:14.24
Scaling Cluster Autoscaler to 1 replicas
[AfterSuite] PASSED [4.570 seconds]
------------------------------

Ran 6 of 6 Specs in 528.462 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (528.46s)
PASS
```

**Review by aaronfern — APPROVED** [review]
