### PR TITLE
Fix targeted scale-in logic

### LINKED ISSUE #159: MCM doesn't remove the machine which CA wants
**What happened**:

We have seen a [case](https://github.tools.sap/kubernetes-live/issues-live/issues/2423) where CAS wants to remove machine A due to low utilization but machine B is removed by MCM when CAS scales down the machinedeployment.
This has happened because machine B was finalized to be removed by CAS some time back and so `ToBeDeleted` taint was placed on the node. But later due to unexpected circumstances (autoscaler restart after priority 1 is set, in which case it clears all `ToBeDeleted` taints, or machineDeployment couldn't be scaled-down etc) autoscaler reverts its decision and removes the `ToBeDeleted` taint.
This leaves the machine B with priority 1 , and later when machine A is asked to be removed machine B is picked up by MCM

**What you expected to happen**:
Scale-down of right machine is expected.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
One solution is to enhance MCM to reset priority to 3 for the machine obj if the `ToBeDeleted` CAS taint on the corresponding node object is removed.

High demand , see live issue # 2423

**Environment**:
g/autoscaler v 1.25.0 and below.

cc @unmarshall

### PR DESCRIPTION
**Pull request by rishabh-11**
**What this PR does / why we need it**:
This PR updates the priority of machines with nodes without `ToBeDeletedTaint` to `3` before calling `DeleteMachines` to scale down the corresponding machine deployment.

**Which issue(s) this PR fixes**:
Fixes #159 

**Special notes for your reviewer**:
This PR does not deal with one case of #159. It is as follows:-
1. All Nodes in a node group: [N1, N2, N3, N4]
At T1, CA marked [N2, N4] with ToBeDeleted taint, added priority=1, and reduced the machine deployment replicas by 2. 
Then CA restarts, which calls `cleanUpIfRequired`, which removes all the taints and resets the priority of N2 and N4 to `3`. By this point, if MCM has not started the deletion process, then it is possible that N2 and N4 are not selected for deletion because MCM selects machines to delete based on priority annotation value.

Following test cases are added for the `DeleteNodes` method:- 
1. Delete single node happy path.
2. Delete single placeholder node happy path.
3. Delete a node with an error in updating machine priority to 1 due to timeout.
4. Delete a node with updateMcD error timeout.
5. Delete a node with updateMcD error resolving b4 timeout.
6. McD is under rolling update.
7. Machine is already in a terminating state. No scale-down should happen.
8. Should not scale down the McD beyond the minimum.
9. Should not delete node if it does not belong to the machine deployment.

Following test cases are added for the `Refresh` method:- 
1. Reset the priority of a machine having a node without `ToBeDeletedTaint` to `3`.
2. Don't reset the priority of a machine having a node with `ToBeDeletedTaint`.
3. Failure to reset the priority of a machine

**The base cluster requirements for IT are updated.**
**The faking (for unit tests of mcm cloud provider implementation) is done for the client only. Listers are not faked**

**Release note**:

```bugfix operator
A bug where MCM removed a machine other than the one , CA wanted , is resolved.
```

```other operator
`machinepriority.machine.sapcloud.io` annotation on machine is now reset to 3 by autoscaler if the corresponding node doesn't have `ToBeDeletedByClusterAutoscaler` taint
```

```other operator
Initial implementation for `Refresh()` method of `CloudProvider` interface done
```

```feature developer
unit tests framework introduced to test implemented methods of `Cloudprovider` and `Nodegroup` interface
```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 1]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
 		}
 		machines = append(machines, ref)
 	}
+
+	retryDeadline := time.Now().Add(maxRetryTimeout)
+	for {
+		updatedMachines := true
+		machinesClient := machinedeployment.mcmManager.machineClient.Machines(machinedeployment.mcmManager.namespace)
+		allMachines, err := machinesClient.List(context.TODO(), v1.ListOptions{LabelSelector: labels.FormatLabels(map[string]string{machineDeploymentNameLabel: machinedeployment.Ref.Name})})
+		if err != nil {
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: instead of returning we can retry on this , till the deadline

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 2]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
 		}
 		ref, err := ReferenceFromProviderID(machinedeployment.mcmManager, node.Spec.ProviderID)
 		if err != nil {
-			return fmt.Errorf("Couldn't find the machine-name from provider-id %s", node.Spec.ProviderID)
+			return fmt.Errorf("couldn't find the machine-name from provider-id %s", node.Spec.ProviderID)
 		}
 		machines = append(machines, ref)
 	}
+
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: we can move this change to `DeleteMachines()` instead of here

- advantages: 
  - easier to read through in one chunk what is done while deleting a machine
  - we should first check if rolling update happening, if yes , then we don't remove the priority 1 annotation from the machines , so this logic should come after [this code](https://github.com/gardener/autoscaler/blob/038296630187c9c78d94f778fe38b1cedb4e9337/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L478-L480)
      - we need to make sure we don't remove prio 1 annotation during rolling update because of the rollout stuck case where ops have to mark machines with prio 1 and scale down machinesets to unblock the situation

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 3]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+					klog.Warningf("could not update priority annotation on existing machine %s; will retry this operation, error: %v", clone.Name, err)
+					time.Sleep(conflictRetryInterval)
+					updatedMachines = false
+					break
+				} else if err != nil {
+					return fmt.Errorf("could not update priority annotation on existing machine %s, error: %v", clone.Name, err)
+				}
+			}
+		}
+		if updatedMachines {
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: you can keep this condition in outer for{ } also 
for !updatedMachines{
}

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 4]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+			return fmt.Errorf("couldn't find the machine-name from provider-id %s", node.Spec.ProviderID)
 		}
 		machines = append(machines, ref)
 	}
+
+	retryDeadline := time.Now().Add(maxRetryTimeout)
+	for {
+		updatedMachines := true
+		machinesClient := machinedeployment.mcmManager.machineClient.Machines(machinedeployment.mcmManager.namespace)
+		allMachines, err := machinesClient.List(context.TODO(), v1.ListOptions{LabelSelector: labels.FormatLabels(map[string]string{machineDeploymentNameLabel: machinedeployment.Ref.Name})})
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: `allMachines` -> `allMachinesForMachineDeployment`  (when this code moves under `DeleteMachines`())

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 5]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+		if err != nil {
+			return fmt.Errorf("couldn't list all machines for machine deployment %s, error: %v", machinedeployment.Ref.Name, err)
+		}
+		for _, machine := range allMachines.Items {
+			if machine.Labels != nil {
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: no need for this nil check for `Labels`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 6]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+				nodeName := machine.Labels[v1alpha1.NodeLabelKey]
+				node, _ := machinedeployment.mcmManager.nodeLister.Get(nodeName)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: consider this error also , send it for a retry till deadline for errors other than `NotFound` errors

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 7]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+				if node != nil {
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: once you have continued `NotFound` , this nil check shouldn't be required.

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 8]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+				} else {
+					annotations[key] = val
+				}
+			}
+			if flag == 1 {
+				clone := machine.DeepCopy()
+				clone.Annotations = annotations
+				_, err := machinesClient.Update(context.TODO(), clone, v1.UpdateOptions{})
+				if err != nil && time.Now().Before(retryDeadline) {
+					klog.Warningf("could not update priority annotation on existing machine %s; will retry this operation, error: %v", clone.Name, err)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: kindly also mention the time in which you'll retry , easier to track in logs then
```suggestion
klog.Warningf("could not reset priority annotation for machine %s; will retry this operation, error: %v", clone.Name, err)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 9]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+					time.Sleep(conflictRetryInterval)
+					updatedMachines = false
+					break
+				} else if err != nil {
+					return fmt.Errorf("could not update priority annotation on existing machine %s, error: %v", clone.Name, err)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]:
```suggestion
return fmt.Errorf("could not reset priority annotation for machine %s, error: %v", clone.Name, err)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 10]
```diff
@@ -371,10 +376,66 @@ func (machinedeployment *MachineDeployment) DeleteNodes(nodes []*apiv1.Node) err
...
+			annotations := make(map[string]string, len(machine.Annotations))
+			flag := 0
+			for key, val := range machine.Annotations {
+				if key == machinePriorityAnnotation && val == "1" {
+					flag = 1
+					annotations[machinePriorityAnnotation] = "3"
+				} else {
+					annotations[key] = val
+				}
+			}
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: instead of a for loop why not use `val,ok` syntax for maps
if val,ok:=map["key"]; ok && val == "1" {
// then update the value in the copy of the map
}

File: cluster-autoscaler/integration/usage.md [hunk 11]
```diff
@@ -3,11 +3,12 @@
 
 1. No user workload to be deployed other than system-components.
 2. All system-components to be able to run on one node
-3. Ideal machine size -> 2 cores CPU, 8Gi memory
-4. 3 machinedeployments/node groups in the cluster should be present, with following min:max limits
-    - machineDeployment1 (1:2)
-    - machineDeployment2 (0:1)
-    - machineDeployment3 (0:1)
+3. Required machine size -> 2 cores CPU, 8Gi memory
+4. 2 workers are needed named `one-zone` and `three-zones` respectively. The 4 machinedeployments/node groups in the cluster should be present, with following `min:max` limits
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/usage.md]:
```suggestion
4. 2 workers pools are needed named `one-zone` and `three-zones` respectively. The 4 machinedeployments/node groups in the cluster should be present, with following `min:max` limits
```

File: cluster-autoscaler/integration/framework.go [hunk 12]
```diff
@@ -103,9 +107,9 @@ func (driver *Driver) adjustNodeGroups() error {
 
 	for index, machineDeployment := range machineDeployments.Items {
 		scaleDownMachineDeployment := machineDeployment.DeepCopy()
-		if index > 0 && machineDeployment.Spec.Replicas != 0 {
+		if (index == 0 || index > 1) && machineDeployment.Spec.Replicas != 0 {
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/framework.go]: instead search by `machineDeployment` name , so that in future we can add more worker groups also easily

File: cluster-autoscaler/integration/integration_test.go [hunk 13]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
 			})
 		})
 	})
+	Describe("testing scale down when priority of other machine is 1", func() {
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
	Describe("testing targeted scale-down done using priority annotation", func() {
```

File: cluster-autoscaler/integration/integration_test.go [hunk 14]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+		Context("set priority of a node to 1 and trigger scale down of another node in the same node group", func() {
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
		Context("when more than one machines have priority 1 in the same nodegrp", func() {
```

File: cluster-autoscaler/integration/integration_test.go [hunk 15]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+			It("should update priority of other node to 3 and remove the correct machine", func() {
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
			It("should scale-down correct node and reset priorities of the rest to 3", func() {
```

File: cluster-autoscaler/integration/integration_test.go [hunk 16]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				By("Deploying a workload")
+				Expect(driver.deployWorkload(int32(1), scaleUpWorkload, workerWithOneZone, false)).To(BeNil())
+				By("Validating Scale up")
+				Eventually(
+					driver.targetCluster.getNumberOfReadyNodes,
+					pollingTimeout,
+					pollingInterval).
+					Should(BeNumerically("==", initialNumberOfNodes+1))
+
+				By("Setting priority annotation on the newly scaled up machine")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Setting priority annotation with value 1 on the machine obj for node A ")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 17]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
 			})
 		})
 	})
+	Describe("testing scale down when priority of other machine is 1", func() {
+		Context("set priority of a node to 1 and trigger scale down of another node in the same node group", func() {
+			It("should update priority of other node to 3 and remove the correct machine", func() {
+				By("Deploying a workload")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Deploying workload A")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 18]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				Expect(driver.deployWorkload(int32(1), scaleUpWorkload, workerWithOneZone, false)).To(BeNil())
+				By("Validating Scale up")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Validating Scale up , node A should join soon")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 19]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				mcList, err := driver.controlCluster.MCMClient.MachineV1alpha1().Machines(controlClusterNamespace).List(context.TODO(), metav1.ListOptions{
+					LabelSelector: metav1.FormatLabelSelector(&metav1.LabelSelector{MatchLabels: map[string]string{mcdNameLabel: mcdName}})})
+				Expect(err).To(BeNil())
+
+				clone := mcList.Items[0].DeepCopy()
+				clone.Annotations[mcmPriorityAnnotation] = "1"
+				_, err = driver.controlCluster.MCMClient.MachineV1alpha1().Machines(controlClusterNamespace).Update(context.TODO(), clone, metav1.UpdateOptions{})
+				Expect(err).To(BeNil())
+
+				By("Deploying another workload")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Deploying workload B")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 20]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				Expect(driver.deployWorkload(int32(1), scaleUpWorkload+"-1", workerWithOneZone, false)).To(BeNil())
+				By("Validating Scale up")
+				Eventually(
+					driver.targetCluster.getNumberOfReadyNodes,
+					pollingTimeout,
+					pollingInterval).
+					Should(BeNumerically("==", initialNumberOfNodes+2))
+
+				By("Scaling down newer workload to zero...")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Scaling down newer workload B to zero...")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 21]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				Expect(driver.scaleWorkload(scaleUpWorkload+"-1", 0)).To(BeNil())
+
+				By("Validating Scale down")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Validating Scale down due to under-utilization")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 22]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				Eventually(
+					driver.targetCluster.getNumberOfReadyNodes,
+					pollingTimeout,
+					pollingInterval).
+					Should(BeNumerically("==", initialNumberOfNodes+1))
+
+				By("Checking that the older node is not removed.")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Validating node A is not removed, and priority is reset to 3")
```

File: cluster-autoscaler/integration/integration_test.go [hunk 23]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				_, err = driver.controlCluster.MCMClient.MachineV1alpha1().Machines(controlClusterNamespace).Get(context.TODO(), clone.Name, metav1.GetOptions{})
+				Expect(err).Should(BeNil())
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go:391]: also validate that priority is reset

File: cluster-autoscaler/integration/integration_test.go [hunk 24]
```diff
@@ -336,4 +333,64 @@ func (driver *Driver) controllerTests() {
...
+				Expect(driver.deployWorkload(int32(1), scaleUpWorkload+"-1", workerWithOneZone, false)).To(BeNil())
+				By("Validating Scale up")
+				Eventually(
+					driver.targetCluster.getNumberOfReadyNodes,
+					pollingTimeout,
+					pollingInterval).
+					Should(BeNumerically("==", initialNumberOfNodes+2))
+
+				By("Scaling down newer workload to zero...")
+				Expect(driver.scaleWorkload(scaleUpWorkload+"-1", 0)).To(BeNil())
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]: name the other one with "-A"
```suggestion
				Expect(driver.scaleWorkload(scaleUpWorkload+"-B", 0)).To(BeNil())
```

File: cluster-autoscaler/integration/usage.md [hunk 25]
```diff
@@ -32,7 +33,7 @@ Cluster Autoscaler integration test suite runs a set of tests against an actual
 	export TARGET_KUBECONFIG=<Path to the kubeconfig file of the Shoot>
 	export CONTROL_KUBECONFIG=<Path to the kubeconfig file of the Seed (or the control plane where the Cluster Autoscaler & Machine deployment objects exists)>
 	export KUBECONFIG=<Path to the kubeconfig file of the Shoot>
-	export VOLUME_ZONE=<zone with zero nodes where the PV needs to be created to perform test>
+	export VOLUME_ZONE=<zone with zero nodes in the worker "three-zones" where the PV needs to be created to perform test>
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/usage.md]:
```suggestion
	export VOLUME_ZONE=<zone with zero nodes in the worker pool "three-zones" where the PV needs to be created to perform test>
```

File: cluster-autoscaler/Makefile [hunk 26]
```diff
@@ -147,7 +148,7 @@ download-kubeconfigs:
 	read SHOOT; \
 	echo "enter cluster provider(gcp|aws|azure|vsphere|openstack|alicloud|metal|equinix-metal)"; \
 	read PROVIDER; \
-	echo "enter zone with zero nodes where the PV needs to be created to perform test"; \
+	echo "enter zone with zero nodes in worker \"three-zones\" where the PV needs to be created to perform test"; \
```
Comment (himanshu-kun) [inline cluster-autoscaler/Makefile]:
```suggestion
	echo "enter zone with zero nodes in worker pool \"three-zones\" where the PV needs to be created to perform test"; \
```

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
kindly avoid using `flag` as it makes the code unreadable
also try to break the main code where you reset priorities into helper functions so its more readable.

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
kindly avoid using `flag` as it makes the code unreadable
also try to break the main code where you reset priorities into helper functions so its more readable.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 27]
```diff
@@ -479,6 +481,45 @@ func (m *McmManager) DeleteMachines(machines []*Ref) error {
...
+				break
+			}
+		}
+		if toBeDeletedTaintPresent {
+			// Don't update priority annotation if the taint is present
+			continue
+		}
+		clone := machine.DeepCopy()
+		val, ok := clone.Annotations[machinePriorityAnnotation]
+		if !ok || val != "3" {
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: don't put annotation if its not there, that is job of mcm , if CA is doing it then MCM might face conflicts leading to more delays in machineCreation by MCM

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 28]
```diff
@@ -479,6 +481,45 @@ func (m *McmManager) DeleteMachines(machines []*Ref) error {
 		return fmt.Errorf("MachineDeployment %s is under rolling update , cannot reduce replica count", commonMachineDeployment.Name)
 	}
 
+	// update priority of all machines except the ones that have the ToBeDeleted taint to 3
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: change the name of the parameter in `DeleteMachines()` from `machines` to `machinesAskedForRemoval` to avoid confusion.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 29]
```diff
@@ -479,6 +481,45 @@ func (m *McmManager) DeleteMachines(machines []*Ref) error {
...
+		}
+		clone := machine.DeepCopy()
+		val, ok := clone.Annotations[machinePriorityAnnotation]
+		if !ok || val != "3" {
+			clone.Annotations[machinePriorityAnnotation] = "3"
+			retryDeadline := time.Now().Add(maxRetryTimeout)
+			for {
+				_, err := m.machineClient.Machines(m.namespace).Update(context.TODO(), clone, metav1.UpdateOptions{})
+				if err != nil && time.Now().Before(retryDeadline) {
+					klog.Warningf("could not update priority annotation on existing machine %s; will retry this operation, error: %v", clone.Name, err)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: mention the time in which retry will be done , will ease debugging

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 30]
```diff
@@ -479,6 +481,45 @@ func (m *McmManager) DeleteMachines(machines []*Ref) error {
...
+	// update priority of all machines except the ones that have the ToBeDeleted taint to 3
+	allMachinesForMachineDeployment, err := m.getMachinesForMachineDeploymentUntilDeadline(md.Name, conflictRetryInterval, time.Now().Add(maxRetryTimeout))
+	if err != nil {
+		return fmt.Errorf("unable to list all machines for node group %s, cannot proceed with scale-in of machines, Error: %v", md.Name, err)
+	}
+	for _, machine := range allMachinesForMachineDeployment.Items {
+		nodeName := machine.Labels[v1alpha1.NodeLabelKey]
+		node, err := m.getNodeForMachineUntilDeadline(nodeName, conflictRetryInterval, time.Now().Add(maxRetryTimeout))
+		if err != nil {
+			return fmt.Errorf("unable to get Node object %s for machine %s, cannot proceed with scale-in of machines, Error: %v", nodeName, machine.Name, err)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: err is also returned in `NotFound` case for node , which will abort the entire `DeleteMachines` 
We can reset the annotation to 3 in a `NotFound` case (even if autoscaler actually wants to delete this node) , because MCM anyways will remove it in `healthTimeout`

File: cluster-autoscaler/integration/framework.go [hunk 31]
```diff
@@ -101,13 +105,20 @@ func (driver *Driver) adjustNodeGroups() error {
 		return err
 	}
 
-	for index, machineDeployment := range machineDeployments.Items {
+	firstMDOfWorkerWithThreeZones := true
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/framework.go]: for better readability
```suggestion
	isFirstMdOfWorkerWithThreeZones := true
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 8 above)
Comment (himanshu-kun) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: kindly commit all these suggestions

File: cluster-autoscaler/integration/framework.go [hunk 32]
```diff
@@ -101,13 +105,20 @@ func (driver *Driver) adjustNodeGroups() error {
...
+			firstMDOfWorkerWithThreeZones = false
 			scaleDownMachineDeployment.Spec.Replicas = 1
+		} else {
+			scaleDownMachineDeployment.Spec.Replicas = 0
 		}
+		//if (index == 0 || index > 1) && machineDeployment.Spec.Replicas != 0 {
+		//	scaleDownMachineDeployment.Spec.Replicas = 0
+		//} else if index == 1 && machineDeployment.Spec.Replicas > 1 {
+		//	scaleDownMachineDeployment.Spec.Replicas = 1
+		//}
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/framework.go]: remove this

File: cluster-autoscaler/integration/integration_test.go [hunk 33]
```diff
@@ -336,4 +333,66 @@ func (driver *Driver) controllerTests() {
...
+				Expect(driver.scaleWorkload(scaleUpWorkload+"-b", 0)).To(BeNil())
+
+				By("Validating Scale down due to under-utilization")
+				Eventually(
+					driver.targetCluster.getNumberOfReadyNodes,
+					pollingTimeout,
+					pollingInterval).
+					Should(BeNumerically("==", initialNumberOfNodes+1))
+
+				By("Checking that the node A' is not removed and it's priority is set to 3")
```
Comment (himanshu-kun) [inline cluster-autoscaler/integration/integration_test.go]:
```suggestion
				By("Checking that the node A is not removed and it's priority is set to 3")
```

**Review by himanshu-kun — CHANGES_REQUESTED** [review]

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 34]
```diff
@@ -445,133 +447,182 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
 		terminatingMachines                 []*v1alpha1.Machine
 		expectedToTerminateMachineNodePairs []machineNameNodeNamePair
 	)
-
-	if len(machines) == 0 {
+	if len(machinesAskedForRemoval) == 0 {
 		return nil
 	}
-	commonMachineDeployment, err := m.GetMachineDeploymentForMachine(machines[0])
+	commonMachineDeployment, err := m.GetMachineDeploymentForMachine(machinesAskedForRemoval[0])
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: There is a lot of repetition resulting in too many API calls. GetMachineDeploymentForMachine already does the following:
1. Gets the machine
2. Figures out the owner MachineSet and gets the MachineSet
3. Figures out the owner MachineDeployment and gets the MachineDeployment

Then `canDeleteMachines` repeats this process for all machines to be deleted again?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 35]
```diff
@@ -445,133 +447,182 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
 }
 
 // DeleteMachines deletes the Machines and also reduces the desired replicas of the Machinedeplyoment in parallel.
-func (m *McmManager) DeleteMachines(machines []*Ref) error {
+func (m *McmManager) DeleteMachines(machinesAskedForRemoval []*Ref) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Minor comment:
These are references to machines that needs to be removed. Therefore variable name should be `targetMachineRefs`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 36]
```diff
@@ -445,133 +447,182 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-	commonMachineDeployment, err := m.GetMachineDeploymentForMachine(machines[0])
+	commonMachineDeployment, err := m.GetMachineDeploymentForMachine(machinesAskedForRemoval[0])
+	if err != nil {
+		return err
+	}
+	if err = m.canDeleteMachines(commonMachineDeployment.Name, machinesAskedForRemoval); err != nil {
+		return err
+	}
+	// update priority of all machines in the machineDeployment to 3 except the ones that have nodes with the ToBeDeleted taint
+	if err = m.resetPriorityOnMachinesWithNodesWithoutToBeDeletedTaintInMachineDeployment(commonMachineDeployment.Name); err != nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: you could written a paragraph as the method name instead ;) 
alternative: `resetPriorityForNotToBeDeletedNodes`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 37]
```diff
@@ -445,133 +447,182 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+			if err = m.updateAnnotationOnMachineUntilDeadline(mclone.Name, machinePriorityAnnotation, "1", conflictRetryInterval, retryDeadline); err != nil {
+				return err
+			}
+			// Break out of loop when update succeeds
+			klog.Infof("Machine %s of machineDeployment %s marked with priority 1 successfully", machine.Name, commonMachineDeployment.Name)
+			break
+		}
+	}
+	// Trying to update the machineDeployment till the deadline
+	updatedReplicas, err := m.scaleDownMachineDeploymentUntilDeadline(commonMachineDeployment.Name, int32(len(machinesAskedForRemoval)-len(terminatingMachines)), conflictRetryInterval, time.Now().Add(maxRetryTimeout))
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: was it not possible to just take the length of expectedToTerminateMachineNodePairs instead bothering to get machines which are already in terminating state and then subtracting from len(machinesAskedForRemoval)?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 38]
```diff
@@ -445,133 +447,182 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+	}
+	if err = m.canDeleteMachines(commonMachineDeployment.Name, machinesAskedForRemoval); err != nil {
+		return err
+	}
+	// update priority of all machines in the machineDeployment to 3 except the ones that have nodes with the ToBeDeleted taint
+	if err = m.resetPriorityOnMachinesWithNodesWithoutToBeDeletedTaintInMachineDeployment(commonMachineDeployment.Name); err != nil {
+		return err
+	}
+	// update priorities of machines to be deleted except the ones already in termination to 1
+	for _, machine := range machinesAskedForRemoval {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: rename machine to machineRef else it becomes very confusing.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 39]
```diff
@@ -813,6 +864,60 @@ func (m *McmManager) getMachineDeploymentUntilDeadline(mdName string, retryInter
 	}
 }
 
+// getMachineUntilDeadline returns error only when fetching the machine has been failing consequently and deadline is crossed
+func (m *McmManager) getMachineUntilDeadline(mcName string, retryInterval time.Duration, deadline time.Time) (*v1alpha1.Machine, error) {
+	for {
+		mc, err := m.machineLister.Machines(m.namespace).Get(mcName)
+		if err != nil && time.Now().Before(deadline) {
+			klog.Warningf("Unable to fetch MachineDeployment object %s, Error: %s, will retry in %s", mcName, err, retryInterval)
+			time.Sleep(retryInterval)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: please do not use `time.Sleep` as it prevents the go runtime to reschedule this go-routine. A thread is blocked and cannot be used for another go-routine. 
We have already coded a retry utility in DWD please use that instead or you can also use the one that comes natively with client-go (https://pkg.go.dev/k8s.io/client-go/util/retry). Same comment for all functions where you are doing the retry

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 35 above)
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: When CA restarts then it calls `cleanUpIfRequired` once and will release all `ToBeDeleted` taints. So now consider the following situation:
All Nodes in a nodegroup: [N1, N2, N3, N4]
1. At T1 CA marked [N2, N4] with `ToBeDeleted` taint. MCM provider added priority=1 and reduced the replicas by 2
2. CA restarts and that calls `cleanUpIfRequired` that removes all the taints. It does not call `DeleteNodes` and therefore `DeleteMachines` is also never called (which is where you are resetting the priorities). In the mean time since both noschedule and tobedeleted taints are removed, workload is scheduled and now MCM goes ahead and deletes the node because we do not check if the `ToBeDeleted` taint is present on a node before deleting the corresponding machine in MCM.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 40]
```diff
@@ -445,133 +447,182 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-			// Break out of loop when update succeeds
-			break
+			machine.Annotations[key] = val
+		} else {
+			machine.Annotations = make(map[string]string)
+			machine.Annotations[key] = val
 		}
 
-		klog.Infof("Machine %s of machineDeployment %s marked with priority 1 successfully", machine.Name, md.Name)
+		_, err = m.machineClient.Machines(machine.Namespace).Update(context.TODO(), machine, metav1.UpdateOptions{})
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: deadline passed in this method is not going to be honoured because you chose to pass context.TODO to Update method and if that method call blocks then deadline is never honoured.

Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [b715441](https://github.com/gardener/autoscaler/pull/215/commits/b715441e904ac9ad31bb8041ab0a5df5e6052f9a)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 35 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: As per our offline discussion, I will add it to the PR description that this test case won't be handled

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 39 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: https://pkg.go.dev/k8s.io/client-go/util/retry also uses `time.Sleep` in its implementation. In DWD, for `retryOnError` we use `time.Sleep`, we use channels and `time.After` as well in other methods, but I think it will be the same thing.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 38 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [03c13fc](https://github.com/gardener/autoscaler/pull/215/commits/03c13fc3b37527d0e3ca8a8571237abdb64ec68f)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 37 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [03c13fc](https://github.com/gardener/autoscaler/pull/215/commits/03c13fc3b37527d0e3ca8a8571237abdb64ec68f)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 36 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [03c13fc](https://github.com/gardener/autoscaler/pull/215/commits/03c13fc3b37527d0e3ca8a8571237abdb64ec68f)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 35 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [03c13fc](https://github.com/gardener/autoscaler/pull/215/commits/03c13fc3b37527d0e3ca8a8571237abdb64ec68f)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 34 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [03c13fc](https://github.com/gardener/autoscaler/pull/215/commits/03c13fc3b37527d0e3ca8a8571237abdb64ec68f)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 39 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Ok if k8s utility is using time.Sleep then it is a bad coding choice. At least in DWD we use time.After and that is better as go scheduler is now able to move out this routine from scheduling onto to a thread till it gets an event on this channel at which time the go-routine is scheduled back. However we should also improve in DWD and not use time.After but create a ticker and stop the ticker in the defer call.

Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [818628e](https://github.com/gardener/autoscaler/pull/215/commits/818628ebcc0a9dd831c382efafaf39fad1a86753)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 41]
```diff
@@ -404,9 +409,9 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
 
 // SetMachineDeploymentSize sets the desired size for the Machinedeployment.
 func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployment, size int64) error {
-	md, err := m.getMachineDeploymentUntilDeadline(machinedeployment.Name, conflictRetryInterval, time.Now().Add(maxRetryTimeout))
+	md, err := m.getMachineDeploymentUntilDeadline(machinedeployment.Name, m.conflictRetryInterval, time.Now().Add(m.maxRetryTimeout))
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: now that mcmManager `m` has `maxRetryTimeout` and `conflictRetryInterval` as part of it, then we shouldn't pass them as parameters to these methods, fix with other similar methods as well.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 42]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+// resetPriorityForNotToBeDeletedMachines resets the priority of machines with nodes without ToBeDeleted taint to 3
+func (m *McmManager) resetPriorityForNotToBeDeletedMachines(mdName string) error {
+	allMachinesForMachineDeployment, err := m.getMachinesForMachineDeploymentUntilDeadline(mdName, m.conflictRetryInterval, time.Now().Add(m.maxRetryTimeout))
+	if err != nil {
+		return fmt.Errorf("unable to list all machines for node group %s, cannot proceed with scale-in of machines, Error: %+v", mdName, err)
+	}
+	var (
+		ctx      context.Context
+		cancelFn context.CancelFunc
+	)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: why do we have to declare a separate var block if we can initialize the variable using := ?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 43]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+						return fmt.Errorf("could not reset priority annotation on machine %s; timed out, error: %+v", clone.Name, err)
+					case <-time.After(m.conflictRetryInterval):
+						klog.Warningf("could not reset priority annotation for machine %s; Error: %+v, will retry the operation", clone.Name, err)
+						continue
+					}
+				}
+				break
+			}
+		}
+		cancelFn()
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: you can create this as inplace / lambda function like ( rough example below)

```
for m:= range machines:
  fn_machine_priority_reset(machine) {
   ctx, cancel := context.WithDeadline...
   defer cancel()

  // remaining code
  }(m)
```

This will save from duplication of `cancel()` in every if case which looks untidy

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 44]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-	retryDeadline := time.Now().Add(maxRetryTimeout)
+// updateAnnotationOnMachineUntilDeadline returns error only when updating the annotations on machine has been failing consequently and deadline is crossed
+func (m *McmManager) updateAnnotationOnMachineUntilDeadline(mcName string, key, val string, retryInterval time.Duration, deadline time.Time) error {
+	ctx, cancelFn := context.WithDeadline(context.Background(), deadline)
+	defer cancelFn()
 	for {
-		// fetch fresh copy of machineDeployment
-		md, err = m.getMachineDeploymentUntilDeadline(commonMachineDeployment.Name, conflictRetryInterval, retryDeadline)
+		machine, err := m.getMachineUntilDeadline(mcName, retryInterval, deadline)
+		clone := machine.DeepCopy()
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: this cloning should be done after checking the `err` returned , as `machine` can be `nil`... not sure if `DeepCopy()` handles `nil` cases.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 45]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+		break
+	}
+	return nil
+}
 
-		mdclone = md.DeepCopy()
-		if (int(mdclone.Spec.Replicas) - len(machines)) < 0 {
-			return fmt.Errorf("Unable to delete machine in MachineDeployment object %s , machine replicas are < 0 ", commonMachineDeployment.Name)
+// scaleDownMachineDeploymentUntilDeadline returns an error only when fetching/updating the machine deployment fails consequently and deadline is crossed or decrease in replica count
+// is more than the current spec.Replicas
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: mention what does this function  return as well

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 46]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+func (m *McmManager) scaleDownMachineDeploymentUntilDeadline(mdName string, scaleDownAmount int, retryInterval time.Duration, deadline time.Time) (int32, error) {
+	var mdclone *v1alpha1.MachineDeployment
+	ctx, cancelFn := context.WithDeadline(context.Background(), deadline)
+	defer cancelFn()
+	for {
+		// fetch fresh copy of machineDeployment
+		md, err := m.getMachineDeploymentUntilDeadline(mdName, retryInterval, deadline)
+		if err != nil {
+			klog.Errorf("Unable to fetch MachineDeployment object %s, Error: %+v", mdName, err)
+			return 0, err
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: in case of failure , it should return the current number of replicas not `0`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 47]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
 		}
-		expectedReplicas := mdclone.Spec.Replicas - int32(len(machines)) + int32(len(terminatingMachines))
+		mdclone = md.DeepCopy()
+		expectedReplicas := mdclone.Spec.Replicas - int32(scaleDownAmount)
 		if expectedReplicas == mdclone.Spec.Replicas {
 			klog.Infof("MachineDeployment %q is already set to %d, skipping the update", mdclone.Name, expectedReplicas)
 			break
+		} else if expectedReplicas < 0 {
+			klog.Errorf("Cannot delete machines in machine deployment %s, expected decrease in replicas %d is more than current replicas %d", mdName, scaleDownAmount, mdclone.Spec.Replicas)
+			return 0, err
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: same as above, shouldn't return `0`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 48]
```diff
@@ -415,163 +420,219 @@ func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-		} else if err != nil {
-			// Timeout occurred
-			klog.Errorf("Unable to update MachineDeployment object %s, Error: %s , timeout occurred", commonMachineDeployment.Name, err)
-			return err
+		_, err = m.machineClient.MachineDeployments(mdclone.Namespace).Update(ctx, mdclone, metav1.UpdateOptions{})
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				klog.Errorf("Unable to update MachineDeployment object %s, Error: %+v , timeout occurred", mdName, err)
+				return 0, err
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: same as above

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 49]
```diff
@@ -798,21 +859,87 @@ func isRollingUpdateFinished(md *v1alpha1.MachineDeployment) bool {
...
+// getMachineUntilDeadline returns error only when fetching the machine has been failing consequently and deadline is crossed
+func (m *McmManager) getMachineUntilDeadline(mcName string, retryInterval time.Duration, deadline time.Time) (*v1alpha1.Machine, error) {
+	ctx, cancelFn := context.WithDeadline(context.Background(), deadline)
+	defer cancelFn()
+	for {
+		mc, err := m.machineLister.Machines(m.namespace).Get(mcName)
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				klog.Errorf("Unable to fetch MachineDeployment object %s, Error: %+v, timeout occurred", mcName, err)
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: error message should have `machine` in the message , check other error messages too..

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 50]
```diff
@@ -798,21 +859,87 @@ func isRollingUpdateFinished(md *v1alpha1.MachineDeployment) bool {
...
+				klog.Warningf("Unable to fetch MachineDeployment object %s, Error: %+v, will retry the operation", mdName, err)
+				continue
+			}
 		}
 		return md, nil
 	}
 }
 
+// getMachineUntilDeadline returns error only when fetching the machine has been failing consequently and deadline is crossed
+func (m *McmManager) getMachineUntilDeadline(mcName string, retryInterval time.Duration, deadline time.Time) (*v1alpha1.Machine, error) {
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: we are fetching `machine(s)` and `node` from cache... which always returns fast , so we shouldn't have a `waitUnitlDeadline` for these.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 51]
```diff
@@ -798,21 +859,87 @@ func isRollingUpdateFinished(md *v1alpha1.MachineDeployment) bool {
...
+		return mc, nil
+	}
+}
+
+// getMachinesForMachineDeploymentUntilDeadline returns error only when fetching the machine list has been failing consequently and deadline is crossed
+func (m *McmManager) getMachinesForMachineDeploymentUntilDeadline(mdName string, retryInterval time.Duration, deadline time.Time) (*v1alpha1.MachineList, error) {
+	ctx, cancelFn := context.WithDeadline(context.Background(), deadline)
+	defer cancelFn()
+	for {
+		ml, err := m.machineClient.Machines(m.namespace).List(ctx, metav1.ListOptions{LabelSelector: labels.FormatLabels(map[string]string{machineDeploymentNameLabel: mdName})})
```
Comment (himanshu-kun) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: use a lister call instead of api server call , if possible here. We should use api server calls only for get of machinedeployment and `update` of anything.

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
should we change `..UntilDeadline` to `...BeforeDeadline` , like `getMachineDeploymentUntilDeadline` -> `getMachineDeploymentBeforeDeadline` 
it would be more readable then, WDYT? 

I have suggested some other changes as well.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 50 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: we have a `getMachineDeploymentUntilDeadline` that has a `waitUntilDeadline` for machine deployments. It also fetches it from the cache.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 41 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 42 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 43 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 44 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 45 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 46 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Returning `0` here because we do not have `spec.Replicas` as the machine deployment get failed,

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 47 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 48 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 49 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 51 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [7824ca9](https://github.com/gardener/autoscaler/pull/215/commits/7824ca90fa42fba9b53f09ec7d7d90c923b3b7b3)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 50 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: removed deadlines for cache calls in [9b7f40d](https://github.com/gardener/autoscaler/pull/215/commits/9b7f40d4fa9dd8371045b4f766f3b62b9b659182)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 45 above)
Comment (himanshu-kun) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: by return I meant , mention the replica count value also its returning.

**Review by himanshu-kun — APPROVED** [review]
/lgtm

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 52]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
 
 // SetMachineDeploymentSize sets the desired size for the Machinedeployment.
 func (m *McmManager) SetMachineDeploymentSize(machinedeployment *MachineDeployment, size int64) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: method argument should use `camelCase` - std golang variable naming convention.
Also since you are fetching the MachineDeployment afresh in this method, all you need is `types.NamespacedName` to be passed for the machine deployment.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 53]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-		return fmt.Errorf("MachineDeployment %s is under rolling update , cannot reduce replica count", md.Name)
-	}
-
-	retryDeadline := time.Now().Add(maxRetryTimeout)
+	ctx, cancelFn := context.WithDeadline(context.Background(), time.Now().Add(m.maxRetryTimeout))
+	defer cancelFn()
 	for {
 		// fetching fresh copy of machineDeployment
-		md, err := m.getMachineDeploymentUntilDeadline(machinedeployment.Name, conflictRetryInterval, retryDeadline)
+		md, err := m.machineDeploymentLister.MachineDeployments(m.namespace).Get(machinedeployment.Name)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Since you are doing this in a loop till the context has timed out, do you not wish to retry fetching the machine deployment if there is an error getting it in the first attempt. The one case where you would want to exit early would be if the error indicates a 404 NotFound. For all other errors would it make sense to not return the error and instead retry?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 54]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
 		if err != nil {
-			klog.Errorf("Unable to fetch MachineDeployment object %s, Error: %s", machinedeployment.Name, err)
+			klog.Errorf("Unable to fetch MachineDeployment object %s, Error: %+v", machinedeployment.Name, err)
 			return err
 		}
-
+		// don't scale down during rolling update, as that could remove ready node with workload
+		if md.Spec.Replicas >= int32(size) && !isRollingUpdateFinished(md) {
+			return fmt.Errorf("MachineDeployment %s is under rolling update , cannot reduce replica count", md.Name)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]:
```suggestion
			return fmt.Errorf("MachineDeployment %s is under rolling update, cannot reduce replica count", md.Name)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 55]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-			// Timeout occurred
-			klog.Errorf("Unable to update MachineDeployment object %s, Error: %s", machinedeployment.Name, err)
-			return err
+		_, err = m.machineClient.MachineDeployments(machinedeployment.Namespace).Update(ctx, clone, metav1.UpdateOptions{})
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				klog.Errorf("Unable to update MachineDeployment object %s, Error: %+v", machinedeployment.Name, err)
+				return err
+			case <-time.After(m.conflictRetryInterval):
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Why do you assume that the err is always a conflict (409) error? The name of the field `conflictRetryInterval` indicates that if there is a conflict then it should retry, however there is no check on the type of error returned.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 53 above)
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: We have in general missed including `context.Context` as the first argument to all methods in `MachineDeploymentLister`.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 56]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-			continue
-		} else if err != nil {
-			// Timeout occurred
-			klog.Errorf("Unable to update MachineDeployment object %s, Error: %s", machinedeployment.Name, err)
-			return err
+		_, err = m.machineClient.MachineDeployments(machinedeployment.Namespace).Update(ctx, clone, metav1.UpdateOptions{})
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				klog.Errorf("Unable to update MachineDeployment object %s, Error: %+v", machinedeployment.Name, err)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: The error message should indicate that a retry will now not happen because the context has timed out. The timeout error can be gotten by invoking `ctx.Err()`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 57]
```diff
@@ -312,7 +317,7 @@ func getAvailableResources(clientBuilder CoreClientBuilder) (map[schema.GroupVer
 
 // CreateMcmManager creates the McmManager
 func CreateMcmManager(discoveryOpts cloudprovider.NodeGroupDiscoveryOptions) (*McmManager, error) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:321]: MCM is short form (acronym) and therefore should be in all-caps. So you should ideally rename:
`CreateMCMManager`
`CreateMCMManagerInternal`
Also one should only delegate to another method when the other method is also exposed. This is called `constructor chaining`. Here an exposed method is delegating to a non-exposed method whose only caller is the same exposed method `CreateMCMManager` therefore i do not find the need to do that.

The correct way if you will is to create 2 constructor functions

```go
func DefaultMCMManager(discoveryOpts cloudprovider.NodeGroupDiscoveryOptions) {
   NewMCMManager(discoveryOpts, defaultConflictRetryInterval, defaultMaxRetryTimeout)
}

func NewMCMManager(discoveryOpts cloudprovider.NodeGroupDiscoveryOptions, conflictRetryInterval, maxRetryTimeout time.Duration) {
  // your code here.
}
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 58]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-			klog.Errorf("Unable to update MachineDeployment object %s, Error: %s", machinedeployment.Name, err)
-			return err
+		_, err = m.machineClient.MachineDeployments(machinedeployment.Namespace).Update(ctx, clone, metav1.UpdateOptions{})
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				klog.Errorf("Unable to update MachineDeployment object %s, Error: %+v", machinedeployment.Name, err)
+				return err
+			case <-time.After(m.conflictRetryInterval):
+				klog.Warningf("Unable to update MachineDeployment object %s, Error: %+v , will retry the operation", machinedeployment.Name, err)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]:
```suggestion
				klog.Warningf("Unable to update MachineDeployment %s, Error: %v , will retry the operation", machinedeployment.Name, err)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 59]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
 // DeleteMachines deletes the Machines and also reduces the desired replicas of the Machinedeplyoment in parallel.
-func (m *McmManager) DeleteMachines(machines []*Ref) error {
-	var (
-		mdclone                             *v1alpha1.MachineDeployment
-		terminatingMachines                 []*v1alpha1.Machine
-		expectedToTerminateMachineNodePairs []machineNameNodeNamePair
-	)
-
-	if len(machines) == 0 {
+func (m *McmManager) DeleteMachines(targetMachineRefs []*Ref) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:431]: Possible to get rid of `Ref` type and instead just use standard `types.NamespacedName` instead? You could also decide to do this separately but since you are anyways touching a lot of code i made this comment. I will leave it up to you to do it as part of this PR or a separate one.

Also why is it a `[]*Ref` and not `[]Ref`?  The reason is that this allows a `nil` value in the slice and then now you have to check for every value to be not nil which is completely unnecessary.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 60]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
 		}
-
 		// Break out of loop when update succeeds
 		break
 	}
 	return nil
 }
 
 // DeleteMachines deletes the Machines and also reduces the desired replicas of the Machinedeplyoment in parallel.
-func (m *McmManager) DeleteMachines(machines []*Ref) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:448]: correct the doc-string. there is a spelling mistake.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 61]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-		expectedToTerminateMachineNodePairs []machineNameNodeNamePair
-	)
-
-	if len(machines) == 0 {
+func (m *McmManager) DeleteMachines(targetMachineRefs []*Ref) error {
+	if len(targetMachineRefs) == 0 {
 		return nil
 	}
-	commonMachineDeployment, err := m.GetMachineDeploymentForMachine(machines[0])
+	commonMachineDeployment, err := m.GetMachineDeploymentForMachine(targetMachineRefs[0])
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:435]: Problems with `GetMachineDeploymentForMachine` (pointing it here since it does not show as changed in this PR):

1. Method accepts a pointer but never checks if it is nil.
2. Its only argument is named as `machine` where as it should have been named as `machineRef`
3. if `machine.Name == nil` then the error msg says that the node does not exist, which is not the correct error message.
4. Error msg when `kube_errors.IsNotFound(err)` is true should refer to the machine which was removed so that in the logs you have some context.
5. If the error is not a `NotFound` error then an error is returned. `fmt.Errorf` gives a warning when you start with a capital letter. Use `fmt.Errorf("failed to retrieve machine %s, Err: %v", machine.Name, err)` Similar is the case for all usages of `fmt.Errorf`
6.  `_, Name := str[0], str[1]` - why use an exported variable and if you are not going to use the 0th index why have it initialized and collected to an ignored identifier?
7. If there is no `NodeGroupSpec` defined for the machine deployment then what gets returned is min=0, max=0. Is this correct?
8. In method `getMachinesForMachineDeployment` you rely upon `machineDeploymentNameLabel` on the `Machine` objects to get machines for a given machine deployment name, but in this method you go from Machine -> OwnerReference -> MachineSet -> OwnerReference, why?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 62]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-				klog.Warningf("Unable to fetch Machine object %s, Error: %s , will retry in %s", machine.Name, err, conflictRetryInterval)
-				time.Sleep(conflictRetryInterval)
-				continue
-			} else if err != nil {
-				// Timeout occurred
-				klog.Errorf("Unable to fetch Machine object %s, Error: %s", machine.Name, err)
-				return err
+// resetPriorityForNotToBeDeletedMachines resets the priority of machines with nodes without ToBeDeleted taint to 3
+func (m *McmManager) resetPriorityForNotToBeDeletedMachines(mdName string) error {
+	allMachinesForMachineDeployment, err := m.getMachinesForMachineDeployment(mdName)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:466]: Can be changed to:
```go
if allMachinesForMachineDeployment, err := m.getMachinesForMachineDeployment(mdName); err != nil {
   return fmt.Errorf("unable to list all machines for node group %s, cannot proceed with scale-in of machines, Error: %+v", mdName, err)
}
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 63]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
 			}
-
-			mclone := machine.DeepCopy()
-
-			if isMachineTerminating(mclone) {
-				terminatingMachines = append(terminatingMachines, mclone)
-			} else {
-				expectedToTerminateMachineNodePairs = append(expectedToTerminateMachineNodePairs, machineNameNodeNamePair{mclone.Name, mclone.Labels["node"]})
+			val, ok := machine.Annotations[machinePriorityAnnotation]
+			if ok && val != "3" {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: this will only work as long as you have only 2 priority levels - 1 and 3. However the concept of priority does not restrict you to have more than 2 levels. If you wish to use 3 as normal/default priority then instead of using a number 3 have a constant which attaches semantic to number 3 priority. This will make the code more understandable.

Also please leave a comment saying that in case we start to support more than 2 priorities then we should make changes if required to this logic.

Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: In general this whole priority thing is not very well implemented and envisioned.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 64]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+				ctx, cancelFn := context.WithDeadline(context.Background(), time.Now().Add(m.maxRetryTimeout))
+				defer cancelFn()
+				for {
+					mc, err := m.machineLister.Machines(m.namespace).Get(machine.Name)
+					if err != nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Same as the another similar comment. Shouldn't you retry in case there is a failure to get the machine. The only error for which a retry should not be required is if it is a 404 and in that case one should ignore the error and continue to update the rest of the machine objects.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 65]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+						klog.Errorf("Unable to fetch Machine object %s, Error: %+v", mc.Name, err)
+						return err
+					}
+					clone := mc.DeepCopy()
+					clone.Annotations[machinePriorityAnnotation] = "3"
+					_, err = m.machineClient.Machines(m.namespace).Update(ctx, clone, metav1.UpdateOptions{})
+					if err != nil {
+						select {
+						case <-ctx.Done():
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: This retry code has now been repeated twice already. This method could have been written in a much more cleaner way, clearly separating retry from what is being retried. Also, what is the need to create an anonymous function here?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 66]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+							return fmt.Errorf("could not reset priority annotation on machine %s; timed out, error: %+v", clone.Name, err)
+						case <-time.After(m.conflictRetryInterval):
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: The default conflict retry interval is 5 sec and the total default timeout is 1 min. This means that you will essentially retry to a max of 12 times? Wow that is a large number of retries. What is the reason for such a large number of retries?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 67]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-
-			mclone := machine.DeepCopy()
-
-			if isMachineTerminating(mclone) {
-				terminatingMachines = append(terminatingMachines, mclone)
-			} else {
-				expectedToTerminateMachineNodePairs = append(expectedToTerminateMachineNodePairs, machineNameNodeNamePair{mclone.Name, mclone.Labels["node"]})
+			val, ok := machine.Annotations[machinePriorityAnnotation]
+			if ok && val != "3" {
+				ctx, cancelFn := context.WithDeadline(context.Background(), time.Now().Add(m.maxRetryTimeout))
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Why not re-use `updateAnnotationOnMachineBeforeDeadline`?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 68]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-					klog.Infof("Machine %q priority is already set to 1, hence skipping the update", machine.Name)
+// prioritizeMachinesForDeletion prioritizes the targeted machines by updating their priority annotation to 1
+func (m *McmManager) prioritizeMachinesForDeletion(targetMachineRefs []*Ref, mdName string) ([]machineNameNodeNamePair, error) {
+	var expectedToTerminateMachineNodePairs []machineNameNodeNamePair
+	for _, machineRef := range targetMachineRefs {
+		// Trying to update the priority of machineRef till m.maxRetryTimeout
+		ctx, cancelFn := context.WithDeadline(context.Background(), time.Now().Add(m.maxRetryTimeout))
+		err := func() error {
+			defer cancelFn()
+			for {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Why use an inner for loop? If this is for retry then that is already done in `updateAnnotationOnMachineBeforeDeadline`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 69]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+				if err = m.updateAnnotationOnMachineBeforeDeadline(ctx, mc.Name, machinePriorityAnnotation, "1"); err != nil {
+					return err
+				}
+				// Break out of loop when update succeeds
+				klog.Infof("Machine %s of machineDeployment %s marked with priority 1 successfully", machineRef.Name, mdName)
+				break
 			}
+			return nil
+		}()
+		if err != nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: If one of the machines could not be updated then why return an error? Either you continue or you rollback, here you decide to abruptly exit mid-way.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 70]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
+		}
+	}
+	return nil
+}
 
-			if mclone.Annotations != nil {
-				if mclone.Annotations[machinePriorityAnnotation] == "1" {
-					klog.Infof("Machine %q priority is already set to 1, hence skipping the update", machine.Name)
+// prioritizeMachinesForDeletion prioritizes the targeted machines by updating their priority annotation to 1
+func (m *McmManager) prioritizeMachinesForDeletion(targetMachineRefs []*Ref, mdName string) ([]machineNameNodeNamePair, error) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: why do you need `machineNameNodeNamePair`. The caller only uses the length of it

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 71]
```diff
@@ -404,174 +409,231 @@ func (m *McmManager) GetMachineDeploymentSize(machinedeployment *MachineDeployme
...
-				time.Sleep(conflictRetryInterval)
-				continue
-			} else if err != nil {
-				// Timeout occurred
-				klog.Errorf("Unable to update Machine object %s, Error: %s", machine.Name, err)
+// updateAnnotationOnMachineBeforeDeadline returns error only when updating the annotations on machine has been failing consequently and deadline is crossed
+func (m *McmManager) updateAnnotationOnMachineBeforeDeadline(ctx context.Context, mcName string, key, val string) error {
+	for {
+		machine, err := m.machineLister.Machines(m.namespace).Get(mcName)
+		if err != nil {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: again the same thing - if there is an error (other than 404 NotFound) should you not retry?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 52 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: I think we should make a separate PR for this. There are other places as well where camel case is not followed

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 55 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: I will rename it to `retryInterval`

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 53 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: In MCM too, the listers do not use context. I think we can ignore this and handle it during controller runtime refactoring

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 57 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:321]: Your point is correct. However, I think we should not address this because it is out of scope of the PR.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 59 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:431]: This was taken from AWS implementation. We can change it in a separate PR

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 61 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:435]: noted for another PR. I will note all the things from the review comments that can be handled in a separate PR. We can then discuss them on a short call.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 62 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:466]: Will need to declare a separate variable for `allMachinesForMachineDeployment`. I think it is better to keep it as it is.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 66 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: I don't think there was any particular to use these defaults. What do you think is a good value for the constants?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 69 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Before prioritizing any machine, we reset the priority of the remaining machines. This will ensure that only the machines that need to be removed are prioritized.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 70 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: It is used in a log.
```
	klog.V(2).Infof("MachineDeployment %s size decreased to %d , should remove following {machineRef, corresponding node} pairs %s ", commonMachineDeployment.Name, updatedReplicas, expectedToTerminateMachineNodePairs)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 71 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 68 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 67 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 65 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 64 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 63 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 60 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:448]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 58 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 56 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 55 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 54 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 53 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: addressed in [9998790](https://github.com/gardener/autoscaler/pull/215/commits/9998790953fb68e9c9abbfb6d6140eb103a38dc5)

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 57 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:321]: Ok. Please note this point and we can address it as part of another PR.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 59 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:431]: Ok

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 61 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:435]: Ok

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 62 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:466]: Ok

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 72]
```diff
@@ -44,7 +44,8 @@ const (
 
 	// GPULabel is the label added to nodes with GPU resource.
 	// TODO: Align on a GPU Label for Gardener.
-	GPULabel = "gardener.cloud/accelerator"
+	GPULabel                   = "gardener.cloud/accelerator"
+	machineDeploymentNameLabel = "name"
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: This constant is used in mcm_manager.go and test_utils.go. Can we not define this only in mcm_manager.go?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 73]
```diff
@@ -315,7 +316,9 @@ func (machinedeployment *MachineDeployment) IncreaseSize(delta int) error {
 	if int(size)+delta > machinedeployment.MaxSize() {
 		return fmt.Errorf("size increase too large - desired:%d max:%d", int(size)+delta, machinedeployment.MaxSize())
 	}
-	return machinedeployment.mcmManager.SetMachineDeploymentSize(machinedeployment, size+int64(delta))
+	return machinedeployment.mcmManager.retry(func(ctx context.Context) (bool, error) {
+		return machinedeployment.mcmManager.SetMachineDeploymentSize(ctx, machinedeployment, size+int64(delta))
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: collect the target size into a variable.
```go
	targetSize := size + int64(delta)
	if targetSize > int64(machinedeployment.MaxSize()) {
		return fmt.Errorf("size increase too large - desired:%d max:%d", targetSize, machinedeployment.MaxSize())
	}
	return machinedeployment.mcmManager.retry(func(ctx context.Context) (bool, error) {
		return machinedeployment.mcmManager.SetMachineDeploymentSize(ctx, machinedeployment, targetSize)
	}, "MachineDeployment", "update", machinedeployment.Name)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 74]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
-			// Timeout occurred
-			klog.Errorf("Unable to update MachineDeployment object %s, Error: %s , timeout occurred", commonMachineDeployment.Name, err)
-			return err
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				klog.Errorf("Context has been cancelled, %s of %s object %s will not be retried, Error: %v , timeout occurred", operation, resourceType, resourceName, ctx.Err())
+				return err
+			case <-tick.C:
+				klog.Warningf("Unable to perform %s on %s resource object %s, Error: %v , will retry the operation", operation, resourceType, resourceName, err)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: you can move this log before starting select clause. This will ensure that you get the log immediately and then you wait for tick.C to return you a msg so that you can retry.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 75]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
+	ctx, cancelFn := context.WithDeadline(context.Background(), time.Now().Add(m.maxRetryTimeout))
+	defer cancelFn()
+	tick := time.NewTicker(m.retryInterval)
+	defer tick.Stop()
 	for {
-		// fetch fresh copy of machineDeployment
-		md, err = m.getMachineDeploymentUntilDeadline(commonMachineDeployment.Name, conflictRetryInterval, retryDeadline)
-		if err != nil {
-			klog.Errorf("Unable to fetch MachineDeployment object %s, Error: %s", commonMachineDeployment.Name, err)
+		retry, err := fn(ctx)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: can we rename this to `canRetry`?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 76]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
+	scaleDownAmount, err := m.prioritizeMachinesForDeletion(targetMachineRefs, commonMachineDeployment.Name)
+	if err != nil {
+		return err
+	}
+	// Trying to update the machineDeployment till the deadline
+	err = m.retry(func(ctx context.Context) (bool, error) {
+		return m.scaleDownMachineDeployment(ctx, commonMachineDeployment.Name, scaleDownAmount)
+	}, "MachineDeployment", "update", commonMachineDeployment.Name)
+	if err != nil {
+		klog.Errorf("unable to scale in machine deployment %s, err:%v", commonMachineDeployment.Name, err)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: everywhere else you have used `Error` in the format string.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 77]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
-					break
+// resetPriorityForNotToBeDeletedMachines resets the priority of machines with nodes without ToBeDeleted taint to 3
+func (m *McmManager) resetPriorityForNotToBeDeletedMachines(mdName string) error {
+	allMachinesForMachineDeployment, err := m.getMachinesForMachineDeployment(mdName)
+	if err != nil {
+		return fmt.Errorf("unable to list all machines for node group %s, cannot proceed with scale-in of machines, Error: %v", mdName, err)
+	}
+	for _, machine := range allMachinesForMachineDeployment {
+		val, ok := machine.Annotations[machinePriorityAnnotation]
+		if ok && val != defaultPriorityValue {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Is it possible that a machine does not have priority annotation? If yes then for that machine would MCM assume a default priority of 3? If yes then this check is fine.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 78]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
+			if err := m.retry(func(ctx context.Context) (bool, error) {
+				nodeName := machine.Labels[v1alpha1.NodeLabelKey]
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:477]: defaultMaxRetryTimeout is set to 1 min. If it is a large machine deployment, then that would mean that for every machine there will be a deadline of 1 min to update annotation. In most of the cases it should be fine, except a case where all updates will fail, maybe because the KAPI is down. So consider that there are 100 machines in a single MD, then this method execution will take at max 100 mins before returning. And the result will be that none of the machines were updated.

Therefore i am not very sure if the usage of timeout should be defined only for `DeleteMachine` or for lower level methods. Can you reconsider this decision?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 79]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
-				return err
+// prioritizeMachinesForDeletion prioritizes the targeted machines by updating their priority annotation to 1
+func (m *McmManager) prioritizeMachinesForDeletion(targetMachineRefs []*Ref, mdName string) (int, error) {
+	var expectedToTerminateMachineNodePairs = make(map[string]string)
+	for _, machineRef := range targetMachineRefs {
+		// Trying to update the priority of machineRef till m.maxRetryTimeout
+		if err := m.retry(func(ctx context.Context) (bool, error) {
+			mc, err := m.machineLister.Machines(m.namespace).Get(machineRef.Name)
+			if err != nil {
+				klog.Errorf("Unable to fetch Machine object %s, Error: %v", machineRef.Name, err)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:510]: Do you wish to handle `NotFound` explicitly?
In other words, If the machine is not found then is a retry required?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 80]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
-				continue
-			} else if err != nil {
-				// Timeout occurred
-				klog.Errorf("Unable to update Machine object %s, Error: %s", machine.Name, err)
-				return err
+// prioritizeMachinesForDeletion prioritizes the targeted machines by updating their priority annotation to 1
+func (m *McmManager) prioritizeMachinesForDeletion(targetMachineRefs []*Ref, mdName string) (int, error) {
+	var expectedToTerminateMachineNodePairs = make(map[string]string)
+	for _, machineRef := range targetMachineRefs {
+		// Trying to update the priority of machineRef till m.maxRetryTimeout
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:502]: Same as the above comment. Here the context deadline is defined for 2 operations
1. Get machine
2. Update machine annotation.

I guess in general the problem is what operations are covered to be completed together within a defined deadline is not so clear.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 81]
```diff
@@ -397,181 +399,191 @@ func (m *McmManager) Cleanup() {
...
+	return true, err
+}
 
-		klog.Infof("Machine %s of machineDeployment %s marked with priority 1 successfully", machine.Name, md.Name)
+// scaleDownMachineDeployment scales down the machine deployment by the provided scaleDownAmount and returns the updated spec.Replicas after scale down.
+func (m *McmManager) scaleDownMachineDeployment(ctx context.Context, mdName string, scaleDownAmount int) (bool, error) {
+	md, err := m.machineDeploymentLister.MachineDeployments(m.namespace).Get(mdName)
+	if err != nil {
+		klog.Errorf("Unable to fetch MachineDeployment object %s, Error: %v", mdName, err)
+		return true, err
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:560]: low level methods returning (bool, error) is not ideal as it ties them via contract to retriability logic. If there was no retry they would never return a bool but just an error. For now i will leave only a comment and will not do further changes.

File: cluster-autoscaler/integration/framework.go [hunk 82]
```diff
@@ -29,10 +29,14 @@ const (
 	dwdAnnotation string = "dependency-watchdog.gardener.cloud/ignore-scaling"
 	// annotaion to skip the scaling down of exrta/unused node.
 	ignoreScaledownAnnotation string = "cluster-autoscaler.kubernetes.io/scale-down-disabled"
```
Comment (unmarshall) [inline cluster-autoscaler/integration/framework.go]: Change `ignoreScaledownAnnotation` to `ignoreScaleDownAnnotation`

File: cluster-autoscaler/integration/framework.go [hunk 83]
```diff
@@ -29,10 +29,14 @@ const (
 	dwdAnnotation string = "dependency-watchdog.gardener.cloud/ignore-scaling"
 	// annotaion to skip the scaling down of exrta/unused node.
```
Comment (unmarshall) [inline cluster-autoscaler/integration/framework.go]:
```suggestion
	// annotation to skip the scaling down of extra/unused node.
```

File: cluster-autoscaler/integration/framework.go [hunk 84]
```diff
@@ -176,20 +181,21 @@ func (driver *Driver) runAutoscaler() {
 		return
 	}
 
-	if len(machineDeployments.Items) > 3 {
+	if len(machineDeployments.Items) > 4 {
```
Comment (unmarshall) [inline cluster-autoscaler/integration/framework.go:184]: I am not sure why 4 MDs are required when you in the test that you have added you only need 1 machine deployment. Can you clarify the reasons for doing so?

File: cluster-autoscaler/integration/framework.go [hunk 85]
```diff
@@ -101,14 +105,15 @@ func (driver *Driver) adjustNodeGroups() error {
...
 	}
 
-	for index, machineDeployment := range machineDeployments.Items {
+	isFirstMDOfWorkerWithThreeZones := true
+	for _, machineDeployment := range machineDeployments.Items {
 		scaleDownMachineDeployment := machineDeployment.DeepCopy()
-		if index > 0 && machineDeployment.Spec.Replicas != 0 {
-			scaleDownMachineDeployment.Spec.Replicas = 0
-		} else if index == 0 && machineDeployment.Spec.Replicas > 1 {
+		if strings.Contains(machineDeployment.Name, workerWithThreeZones) && isFirstMDOfWorkerWithThreeZones {
```
Comment (unmarshall) [inline cluster-autoscaler/integration/framework.go:111]: not the nicest ways of doing this but for now this will work.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 78 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:477]: I think this can be solved by changing the `defaultMaxRetryTimeout`. We can keep it as it is for now and change it if we encounter any problems. Also, as soon as one machine encounters an error, we will return the error instead of trying for other machines. So in case of API server not responding, the return time will be `retryTimeout`.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 80 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:502]: The get and update operations are to be done within a single deadline. This is followed everywhere in the mcm provider implementation and I don't see a problem with it, so I did not change it.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 77 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: MCM assumes a default priority of 3 for all machines without the annotation

File: cluster-autoscaler/integration/framework.go (hunk 84 above)
Comment (rishabh-11) [reply cluster-autoscaler/integration/framework.go:184]: The IT that I have added needs both workloads to be deployed on nodes in the same machine deployment. I need a worker pool with 1 zone for this to be absolutely certain. If there are three zones, then one workload can go to one zone, and the other one can go to the other zone. In the current setup, we deploy a workload to a worker, not a specific machine deployment.

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 86]
```diff
@@ -0,0 +1,592 @@
...
+	fakediscovery "k8s.io/client-go/discovery/fake"
+	k8sfake "k8s.io/client-go/kubernetes/fake"
+	policyv1beta1 "k8s.io/client-go/kubernetes/typed/policy/v1beta1"
+	fakepolicyv1beta1 "k8s.io/client-go/kubernetes/typed/policy/v1beta1/fake"
+	k8stesting "k8s.io/client-go/testing"
+)
+
+// FakeObjectTracker implements both k8stesting.ObjectTracker as well as watch.Interface.
+type FakeObjectTracker struct {
+	*watch.FakeWatcher
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go:47]: It is not clear why *watch.FakeWatcher is embedded into the struct along with a slice of `watcher` structs.
@himanshu-kun  can you clarify as @rishabh-11 also does not know?

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 87]
```diff
@@ -0,0 +1,592 @@
...
+// does not propagate the eviction name.
+type FakeEvictions struct {
+	*fakepolicyv1beta1.FakePolicyV1beta1
+	ns string
+}
+
+// Evict overrides the fakepolicyv1beta1.FakeEvictions to override the
+// Policy implementation. This is because the default Policy fake implementation
+// does not propagate the eviction name.
+func (c *FakeEvictions) Evict(ctx context.Context, eviction *apipolicyv1beta1.Eviction) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]:
```suggestion
func (c *FakeEvictions) Evict(_ context.Context, eviction *apipolicyv1beta1.Eviction) error {
```

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 88]
```diff
@@ -0,0 +1,592 @@
...
+// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
+// without applying any validations and/or defaults. It shouldn't be considered a replacement
+// for a real clientset and is mostly useful in simple unit tests.
+func NewCoreClientSet(objects ...runtime.Object) (*Clientset, *FakeObjectTracker) {
+
+	var scheme = runtime.NewScheme()
+	var codecs = serializer.NewCodecFactory(scheme)
+
+	metav1.AddToGroupVersion(scheme, schema.GroupVersion{Version: "v1"})
+	k8sfake.AddToScheme(scheme)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: returns an error, if you wish to ignore it then make it explicit.
```go
_ = k8sfake.AddToScheme(scheme)
```

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 89]
```diff
@@ -0,0 +1,592 @@
...
+		ControlMachine: controlMachine,
+		TargetCore:     targetCore,
+	}
+
+	return fakeObjectTrackers
+}
+
+// Start starts all object trackers as go routines
+func (o *FakeObjectTrackers) Start() {
+	go o.ControlMachine.Start()
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]:
```suggestion
	go func() {
		err := o.ControlMachine.Start()
		if err != nil {
		   klog.Errorf("failed to start machine object tracker, Err: %v", err)	
		}
	}()
```

Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: Similarly for other object trackers as well.

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 90]
```diff
@@ -0,0 +1,592 @@
...
+	if t.fakingOptions.failAll != nil {
+		err := t.fakingOptions.failAll.RunFakeInvocations()
+		if err != nil {
+			return nil, err
+		}
+	}
+	return t.delegatee.Watch(gvr, name)
+}
+
+func (t *FakeObjectTracker) watchReactionfunc(action k8stesting.Action) (bool, watch.Interface, error) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: use camel case `watchReactionFunc`

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 91]
```diff
@@ -0,0 +1,592 @@
...
+	return nil
+}
+
+// IsFakingEnabled will return true if counter is positive for the fake response
+func (o *FakeResponse) IsFakingEnabled() bool {
+	return o.counter > 0
+}
+
+// SetFailAtFakeResourceActions sets up the errorMessage to be returned on specific calls
+func (o *fakingOptions) SetFailAtFakeResourceActions(resourceActions *ResourceActions) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: Any reason this function returns an error?

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 92]
```diff
@@ -0,0 +1,592 @@
...
+	o.failAt = resourceActions
+	return nil
+}
+
+// SetFailAllFakeResponse sets the error message for all calls from the client
+func (o *fakingOptions) SetFailAllFakeResponse(response *FakeResponse) error {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: Any reason this function return an error?

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 93]
```diff
@@ -0,0 +1,592 @@
...
+// Add receives an add event with the object
+func (t *FakeObjectTracker) Add(obj runtime.Object) error {
+	if t.fakingOptions.failAll != nil {
+		err := t.fakingOptions.failAll.RunFakeInvocations()
+		if err != nil {
+			return err
+		}
+	}
+
+	return t.delegatee.Add(obj)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go:63]: There is no handling of fakingOptions.failAt in this method. Is it not required?

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 94]
```diff
@@ -0,0 +1,592 @@
...
+// Create receives an create event with the object
+func (t *FakeObjectTracker) Create(gvr schema.GroupVersionResource, obj runtime.Object, ns string) error {
+	if t.fakingOptions.failAll != nil {
+		err := t.fakingOptions.failAll.RunFakeInvocations()
+		if err != nil {
+			return err
+		}
+	}
+
+	err := t.delegatee.Create(gvr, obj, ns)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: There is no handling of fakingOptions.failAt in this method. Is it not required?

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 95]
```diff
@@ -0,0 +1,592 @@
...
+func (t *FakeObjectTracker) Delete(gvr schema.GroupVersionResource, ns, name string) error {
+	if t.fakingOptions.failAll != nil {
+		err := t.fakingOptions.failAll.RunFakeInvocations()
+		if err != nil {
+			return err
+		}
+	}
+
+	obj, errGet := t.delegatee.Get(gvr, ns, name)
+	err := t.delegatee.Delete(gvr, ns, name)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: There is no handling of fakingOptions.failAt in this method. Is it not required?

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 96]
```diff
@@ -0,0 +1,592 @@
...
+
+// Watch receives an watch event with the object
+func (t *FakeObjectTracker) Watch(gvr schema.GroupVersionResource, name string) (watch.Interface, error) {
+	if t.fakingOptions.failAll != nil {
+		err := t.fakingOptions.failAll.RunFakeInvocations()
+		if err != nil {
+			return nil, err
+		}
+	}
+	return t.delegatee.Watch(gvr, name)
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go:160]: There is no handling of fakingOptions.failAt in this method. Is it not required?

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 97]
```diff
@@ -397,181 +401,196 @@ func (m *McmManager) Cleanup() {
...
+	}
+	for _, machine := range allMachinesForMachineDeployment {
+		val, ok := machine.Annotations[machinePriorityAnnotation]
+		if ok && val != defaultPriorityValue {
+			if err := m.retry(func(ctx context.Context) (bool, error) {
+				nodeName := machine.Labels[v1alpha1.NodeLabelKey]
+				node, err := m.nodeLister.Get(nodeName)
+				if err != nil && !kube_errors.IsNotFound(err) {
+					return true, fmt.Errorf("unable to get Node object %s for machine %s, Error: %v", nodeName, machine.Name, err)
+				} else if err == nil && taints.HasToBeDeletedTaint(node) {
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:481]: `err == nil` check is redundant.  You can just use the following:
```go
if err != nil && !kube_errors.IsNotFound(err) {
  return true, fmt.Errorf("unable to get Node object %s for machine %s, Error: %v", nodeName, machine.Name, err)
}
if taints.HasToBeDeletedTaint(node) {
 return false, nil
}
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 78 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:477]: I am not sure that is the right behavior. Shouldn't you try and update the annotations for as many machines as possible and then return a collective error? I am still not sure if retry should be at the machine level.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 80 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:502]: ok

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 97 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:481]: The nil check is required because if the error is a `NotFound` error, then no node object will be present. I can take the `IsNotFound` check inside the if block and remove the nil check.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 78 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:477]: I don't see an advantage in using collective error in this case. The Refresh method will return an error even if one update call fails. So, in any case, another reconciliation will be needed. If the API server is down, all the update calls will fail with the same error and returning a collective error in the logs might make them bloated.

Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:477]: In the refresh method shouldn't be a best effort to reset priority annotation value to 3 for as many machines as possible? This way every run of `refresh` method will then only deal with the remaining ones that could not be updated before. in the current case lets say the first update always fails for some reason, then no other machine will ever get the annotation value changed. 

Collective error is only meaningful if you provide best effort update of annotation on machines. This means that you go on even if there are some machines which could not be updated. A simple use of `errors.Join` would suffice here.

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go (hunk 86 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go:47]: The `fakeObjectTracker` is used to create the `fakeClient`, which is then used to create the `Informers`. The watcher slice is filled dynamically when the `watchReactionFunc` is called by the informer of the individual resource type. So for each resourceType (Machine, MachineDeployment etc.), there will be a separate watcher; hence, we need a slice of watchers in the `fakeObjectTracker`. The `*watch.FakeWatcher` will create an event on a result channel that the `Start` method of the `fakeObjectTracker` will read from and pass to all the watchers. The watcher which can handle the event will raise an event and populate its own result channel from where the respective controllers will pick the event and reconcile the corresponding object.

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go [hunk 98]
```diff
@@ -0,0 +1,592 @@
...
+		}
+	}
+
+	err := t.delegatee.Create(gvr, obj, ns)
+	if err != nil {
+		return err
+	}
+
+	if t.FakeWatcher == nil {
+		return errors.New("Error sending event on a tracker with no watch support")
```
Comment (unmarshall) [inline cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go]: watch for goland warnings so that these small things can be taken care before filing the PR.
errors.New recommends to use small case starting letter. There are other occurrences as well. Please fix all.

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go (hunk 86 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go:47]: Ok one more doubt. You call `watchReactorFunc` from 2 places and in both the places you have set the resource to "*" which i presume means all resource types, right? This means there is one registered `watchReactorFunc` only which gets added to the upstream `Fake.WatchReactionChain`. So when `Fake.InvokesWatch` is called then it will just fine one `WatchReactor` for all resources. Therefore your statement: `So for each resourceType (Machine, MachineDeployment etc.), there will be a separate watcher; hence, we need a slice of watchers in the fakeObjectTracker` is not completely understood.

File: cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go (hunk 93 above)
Comment (rishabh-11) [reply cluster-autoscaler/cloudprovider/mcm/fakeclient/client.go:63]: I will update the `failAt` function only for `Get` and `Update` calls, as CA will not use `Create` and `Delete` calls. They can be later added if needed.

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go (hunk 78 above)
Comment (unmarshall) [reply cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:477]: Ok for now we have decided to return an error from `resetPriorityForNotToBeDeletedMachines` knowing that any error returned when updating annotation on machines will cause the `RunOnce` flow to be aborted and retried after 10s. Any need for a scale-up which is handled post call to `Refresh` will also get delayed. Resetting annotations is only required during a scale-down flow and the side effect of using `Refresh` method is that failure to do that would impact the overall `RunOnce` reconciliation flow.

We should watch for issues due to this and make changes if required later.

**Review by unmarshall — APPROVED** [review]
/lgtm

**Review by himanshu-kun — APPROVED** [review]
/lgtm
