### PR TITLE
Fixing the issue where a rapid scale up and scale down can result in a cordoned machine in the cluster

### LINKED ISSUE #1085: Rapid scale up and scale down of a MCD result in a cordoned machine
**How to categorize this issue?**

/area auto-scaling
/kind bug
/priority 3

**What happened**:
We found a bug recently where a rapid scale up and scale down can result in a cordoned machine in the cluster.
This is due to the scale down logic we have with CA, and the recent changes to `manageReplicas()` in the machineSet controller

The case happens when CA scales down a MCD followed quickly with scaling up the same MCD before the MCD controller notices the replica change and start reconciliation. The result is the MCD ending up with the same number of replicas that it started off with, causing the MCD controller not to have any work to do since from it's point of view, the MCD replicas have not changed.
As part of the scale down operation, CA will cordon an underutilised node. This node just remains part of the cluster as MCM makes no further attempt to remove it

Problem example
```
T0:
	We have a mcd with 6 replicas and machines M1…M6
	MCD rep=6

T1:
	CA finds M1 unneeded. Reduces mcd replicas to 5, adds a mc (MC1) to trigger-for-deletion annotation on MCD, and cordons this machine
	MCD rep=5; trigger-for-deletion-annotation=M1
	M1 cordoned by CA
	(MCD controller does not run - for whatever reason)

T2: 
	CA increasesMCD rep=6 
	(MCD controller still does not run - for whatever reason)

T3:
	MCD controller start here
	sees that rep=6 (no change). No work done
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by r4mek**
**What this PR does / why we need it**:
This PR contains a fix for the issue where a rapid scale up and scale down can result in a cordoned machine in the cluster.

The case happens when CA scales down a MCD followed quickly with scaling up the same MCD before the MCD controller notices the replica change and start reconciliation. The result is the MCD ending up with the same number of replicas that it started off with, causing the MCD controller not to have any work to do since from it's point of view, the MCD replicas have not changed.
As part of the scale down operation, CA will cordon an underutilised node. This node just remains part of the cluster as MCM makes no further attempt to remove it

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/machine-controller-manager/issues/1085

**Special notes for your reviewer**:
There is also a PR raised on `gardener/machine-controller-manager` which has the changes from the MCM and is also required to fix the issue. PR(https://github.com/gardener/machine-controller-manager/pull/1087)

**Release note**:

```other operator
Fixing the issue where a rapid scale up and scale down can result in a cordoned machine in the cluster
```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 1]
```diff
@@ -577,14 +577,23 @@ func (ngImpl *nodeGroup) AtomicIncreaseSize(delta int) error {
...
 func getMachineNamesTriggeredForDeletion(mcd *v1alpha1.MachineDeployment) []string {
-	if mcd.Annotations == nil || mcd.Annotations[machineutils.TriggerDeletionByMCM] == "" {
+	if mcd == nil || mcd.Annotations[machineutils.TriggerDeletionByMCM] == "" {
 		return nil
 	}
-	return strings.Split(mcd.Annotations[machineutils.TriggerDeletionByMCM], ",")
+	machineNamesWithTimestamps := strings.Split(mcd.Annotations[machineutils.TriggerDeletionByMCM], ",")
+	machineNames := make([]string, 0, len(machineNamesWithTimestamps))
+	for _, machineNameWithTimestamp := range machineNamesWithTimestamps {
+		machineNames = append(machineNames, strings.Split(machineNameWithTimestamp, "~")[0])
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Please check for length of `strings.Split(machineNameWithTimestamp, "~")` and log an error if the result is not as expected

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 2]
```diff
@@ -577,14 +577,23 @@ func (ngImpl *nodeGroup) AtomicIncreaseSize(delta int) error {
...
 // TODO: Move to using MCM annotations.CreateMachinesTriggeredForDeletionAnnotValue after MCM release
-func createMachinesTriggeredForDeletionAnnotValue(machineNames []string) string {
+func createMachinesTriggeredForDeletionAnnotValue(mcd *v1alpha1.MachineDeployment, machineNames []string) string {
+	timestamp := time.Now().Format(time.RFC3339)
 	slices.Sort(machineNames)
-	return strings.Join(machineNames, ",")
+	if mcd != nil && mcd.Annotations[machineutils.TriggerDeletionByMCM] != "" {
+		return mcd.Annotations[machineutils.TriggerDeletionByMCM] + "," + strings.Join(machineNames, fmt.Sprintf("~%s,", timestamp)) + fmt.Sprintf("~%s", timestamp)
+	}
+	return strings.Join(machineNames, fmt.Sprintf("~%s,", timestamp)) + fmt.Sprintf("~%s", timestamp)
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:599]: Please add a variable `separator` for `fmt.Sprintf("~%s,", timestamp)`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 3]
```diff
@@ -577,14 +577,23 @@ func (ngImpl *nodeGroup) AtomicIncreaseSize(delta int) error {
...
+	machineNames := make([]string, 0, len(machineNamesWithTimestamps))
+	for _, machineNameWithTimestamp := range machineNamesWithTimestamps {
+		machineNames = append(machineNames, strings.Split(machineNameWithTimestamp, "~")[0])
+	}
+	return machineNames
 }
 
 // TODO: Move to using MCM annotations.CreateMachinesTriggeredForDeletionAnnotValue after MCM release
-func createMachinesTriggeredForDeletionAnnotValue(machineNames []string) string {
+func createMachinesTriggeredForDeletionAnnotValue(mcd *v1alpha1.MachineDeployment, machineNames []string) string {
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Please update the godoc with an example

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 4]
```diff
@@ -577,14 +577,23 @@ func (ngImpl *nodeGroup) AtomicIncreaseSize(delta int) error {
...
-	return strings.Split(mcd.Annotations[machineutils.TriggerDeletionByMCM], ",")
+	machineNamesWithTimestamps := strings.Split(mcd.Annotations[machineutils.TriggerDeletionByMCM], ",")
+	machineNames := make([]string, 0, len(machineNamesWithTimestamps))
+	for _, machineNameWithTimestamp := range machineNamesWithTimestamps {
+		machineNames = append(machineNames, strings.Split(machineNameWithTimestamp, "~")[0])
+	}
+	return machineNames
 }
 
 // TODO: Move to using MCM annotations.CreateMachinesTriggeredForDeletionAnnotValue after MCM release
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: Please remove the TODOs if not relevant

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 3 above)
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: This func does not need to accept a mcd object, change the func definition to the following
`getNextTriggeredForDeletionAnnotValue(currentAnnotValue string, markTime time.Time, machineNames []string) string`
Let the caller add the annotation to the mcd

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 5]
```diff
@@ -1150,7 +1149,8 @@ func computeScaleDownData(md *v1alpha1.MachineDeployment, machineNamesForDeletio
 		if mdCopy.Annotations == nil {
 			mdCopy.Annotations = make(map[string]string)
 		}
-		triggerDeletionAnnotValue := createMachinesTriggeredForDeletionAnnotValue(toBeMarkedSet.UnsortedList())
+		mdCopy.Annotations[machineutils.LastReplicaChangeAnnotation] = time.Now().Format(time.RFC3339)
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go]: Please pass this same time to `createMachinesTriggeredForDeletionAnnotValue()`

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go [hunk 6]
```diff
@@ -575,16 +575,26 @@ func (ngImpl *nodeGroup) AtomicIncreaseSize(delta int) error {
...
+	if mcd == nil || mcd.Annotations[machineutils.TriggerDeletionByMCM] == "" {
 		return nil
 	}
-	return strings.Split(mcd.Annotations[machineutils.TriggerDeletionByMCM], ",")
+	machineNamesWithTimestamps := strings.Split(mcd.Annotations[machineutils.TriggerDeletionByMCM], ",")
+	machineNames := make([]string, 0, len(machineNamesWithTimestamps))
+	for _, machineNameWithTimestamp := range machineNamesWithTimestamps {
+		parts := strings.Split(machineNameWithTimestamp, "~")
+		if len(parts) != 2 {
+			klog.Errorf("Unexpected format for machineNameWithTimestamp %q in annotation %q of MachineDeployment %q, expected format is <machineName>~<timestamp>", machineNameWithTimestamp, machineutils.TriggerDeletionByMCM, mcd.Name)
```
Comment (aaronfern) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go]: nit
```suggestion
			klog.Errorf("unexpected format for machineNameWithTimestamp %q in annotation %q of MachineDeployment %q, expected format is <machineName>~<timestamp>", machineNameWithTimestamp, machineutils.TriggerDeletionByMCM, mcd.Name)
```

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go (hunk 2 above)
Comment (aaronfern) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:599]: This is not resolved yet

```suggestion
    separator := fmt.Sprintf("~%s,", timestamp)
	return strings.Join(machineNames, separator) + separator
```

Comment (r4mek) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:599]: There are 2 different strings `fmt.Sprintf("~%s,", timestamp)` and `fmt.Sprintf("~%s", timestamp)` and are only used once. Do you want me to create 2 different variables?

File: cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go [hunk 7]
```diff
@@ -397,8 +397,7 @@ func TestRefresh(t *testing.T) {
 				mcmDeployment:      newMCMDeployment(1),
```
Comment (gagan16k) [inline cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go:397]: Out of scope of the PR, but L394 still uses the old annotation format

Comment (r4mek) [reply cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go:397]: I had kept it for testing backward compatibility

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager_test.go [hunk 8]
```diff
@@ -232,7 +235,7 @@ func TestComputeScaledownData(t *testing.T) {
 
 		machineNamesForDeletion := []string{"n1"}
 		data := computeScaleDownData(md, machineNamesForDeletion)
-		assert.Equal(t, createMachinesTriggeredForDeletionAnnotValue(machineNamesForDeletion), data.RevisedMachineDeployment.Annotations[machineutils.TriggerDeletionByMCM])
+		assert.Equal(t, strings.Split(createMachinesTriggeredForDeletionAnnotValue(machineNamesForDeletion, time.Now().Format(time.RFC3339)), "~")[0], strings.Split(data.RevisedMachineDeployment.Annotations[machineutils.TriggerDeletionByMCM], "~")[0])
```
Comment (elankath) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager_test.go:238]: Would prefer to use intermediate local variables here for readability & legibility instead of long complicated expressions. can take a note to do this later if you are out of time.

**Review by aaronfern — APPROVED** [review]
/lgtm
