### PR TITLE
Avoids panics when VM type isn't found during scale from zero

### LINKED ISSUE #76: panic: runtime error: invalid memory address or nil pointer dereference
**What happened**:

```
$ k -n shoot--it--tmk63-q6p get po cluster-autoscaler-8b4c75dd8-cbrrb
NAME                                 READY   STATUS   RESTARTS   AGE
cluster-autoscaler-8b4c75dd8-cbrrb   0/1     Error    7          12m
```

```
$ k -n shoot--it--tmk63-q6p logs cluster-autoscaler-8b4c75dd8-cbrrb -p

I0511 08:17:50.779956       1 main.go:277] Registered cleanup signal handler
I0511 08:17:50.779994       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0511 08:17:50.780026       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 26.401µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2a3de5b]

goroutine 114 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/mcm.(*McmManager).GetMachineDeploymentNodeTemplate(0xc000bb56c0, 0xc0007ba300, 0xc000bb56c0, 0xc000581800, 0x7ff5670d9108)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:687 +0xb9b
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/mcm.(*MachineDeployment).TemplateNodeInfo(0xc0007ba300, 0x7ffc8cf14a9c, 0x1c, 0xc001331160)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go:386 +0x38
k8s.io/autoscaler/cluster-autoscaler/core/utils.GetNodeInfoFromTemplate(0x3c47ea0, 0xc0007ba300, 0xc00092c400, 0x5, 0x8, 0x3bde2e0, 0xc000a65340, 0xc000a9c4b0, 0x0, 0x0, ...)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/core/utils/utils.go:170 +0x7d
k8s.io/autoscaler/cluster-autoscaler/core/utils.GetNodeInfosForGroups(0xc0009ae650, 0x2, 0x2, 0xc000a9c810, 0x3c3fc80, 0xc000a9c330, 0x3c3ba00, 0xc000e60000, 0xc00092c400, 0x5, ...)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/core/utils/utils.go:114 +0x8b2
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc001302b40, 0xc01ead4e2e80a308, 0x27314e48b, 0x5653ca0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:268 +0x994
main.run(0xc00077e230)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/main.go:352 +0x2d7
main.main.func2(0x3bf36e0, 0xc0004d8800)
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/main.go:431 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/tmp/build/80754af9/git-gardener.autoscaler-machine-controller-manager-provider.machine-controller-manager-provider/tmp/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:208 +0x113
```

**What you expected to happen**:

No panic

**How to reproduce it (as minimally and precisely as possible)**:

Not clear for now.

**Anything else we need to know**:

**Environment**:
Image: `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler:v0.16.0`

### PR DESCRIPTION
**Pull request by prashanth26**
- Cluster autoscaler was trying to fetch VM details for AWS VMs instead of required Azure VMs for MCM (OOT) provider Azure. This lead to panics. Now, it fetches the details from the correct provider VM map.
- This PR also improves error handling in such scenarios to not panic.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/autoscaler/issues/76

**Special notes for your reviewer**:

**Release note**:

```bugfix developer
Avoids panics when VM type isn't found during scale from zero
```
```bugfix developer
Fetches the VM from the correct map for MCM provider Azure and hence doesn't panic anymore
```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/mcm/mcm_manager.go [hunk 1]
```diff
@@ -681,8 +690,10 @@ func (m *McmManager) GetMachineDeploymentNodeTemplate(machinedeployment *Machine
 			if err != nil {
 				return nil, fmt.Errorf("Unable to convert from %s to %s for %s, Error: %v", kindMachineClass, providerAzure, machinedeployment.Name, err)
 			}
-
-			azureInstance := aws.InstanceTypes[providerSpec.Properties.HardwareProfile.VMSize]
+			azureInstance, exists := azure.InstanceTypes[providerSpec.Properties.HardwareProfile.VMSize]
```
Comment (prashanth26) [inline cluster-autoscaler/cloudprovider/mcm/mcm_manager.go:693]: The key change causing the panic is here, where it was fetching AWS details for Azure VMs.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@prashanth26 , can you please file a cherry-pick and cut a `v1.16.1` release? Thank you in advance!

**Comment by prashanth26** [comment]
> @prashanth26 , can you please file a cherry-pick and cut a `v1.16.1` release? Thank you in advance!

Yes, on it. Thanks.

**Comment by prashanth26** [comment]
Also tested this change locally. Scale from zero seems to work as before/expected now. No more panics.

```
I0511 08:53:08.279888       1 scale_up.go:460] Estimated 1 nodes needed in shoot--xxx--yyy-scale0-z3
I0511 08:53:08.279919       1 scale_up.go:574] Final scale-up plan: [{shoot--xxx--yyy-scale0-z3 0->1 (max: 2)}]
I0511 08:53:08.279935       1 scale_up.go:663] Scale-up: setting group shoot--xxx--yyy-scale0-z3 size to 1
```

**Review by AxiomSamarth — APPROVED** [review]
